services:
  app:
    image: aftermarketmonkey_be:latest
    build:
      context: .
    restart: always
    env_file:
      - ./.env.app.${DEPLOY_ENV:-production}
    ports:
      - "8005:8000"
    depends_on:
      - cache-redis



  cache-redis:
    image: redis:7.2-rc1-alpine
    volumes:
      - redis_data:/var/lib/redis/data/
    ports:
      - "6385:6379"
    restart: always

  meilisearch:
    image: getmeili/meilisearch:v1.11
    volumes:
      - meilisearch_data:/meili_data
    ports:
      - "7700:7700"
    env_file:
      - ./.env.app.${DEPLOY_ENV:-production}
    environment:
      - MEILI_ENV=${DEPLOY_ENV:-production}
    restart: always


volumes:
  redis_data:
  meilisearch_data:
