"""
Populate ``MasterPart.product_type`` (wheel / tire / part) from every distributor that ships a
usable signal. The rules themselves live in ``src.integrations.utils.product_type``; this module
is the machinery that feeds them 3.9M ``provider_parts`` rows and resolves the results.

**A wrong label is worse than no label.** Two things enforce that:

  * A source only ever produces a verdict its rules actually decided. Everything else is left
    alone, and the run reports the size of that gap rather than filling it.
  * If the distributors that agree on the *best available tier* do not agree with each other,
    the part is left NULL and counted as a conflict. We would rather hand back "we don't know"
    than pick a winner between a distributor calling something a wheel and another calling it a
    part -- that disagreement usually means one feed is miscategorised or the two rows were
    merged onto one MasterPart by mistake, and both are worth a human look.

Two phases, because a master part can be sold by up to 9 distributors and the answer depends on
all of them:

  1. **Collect.** Page each provider's ``provider_parts`` by ``(provider_id, id)`` -- the index
     ``0157`` added -- joining out to that distributor's raw table, and write one candidate row
     per verdict into ``master_part_type_candidates``.
  2. **Resolve.** One SQL statement per run: group candidates by master part, keep the best
     (lowest) tier, and write it back only where that tier is unanimous.

The staging table is deliberately not a Django model. It is a derived artifact rebuilt from
scratch on every run, so it carries no migration and is created ``UNLOGGED`` (no WAL, not
crash-safe, which is exactly right for something regenerated by re-running the command). It is
left in place afterwards on purpose: when a part's type looks wrong, the first question is
always "what did each distributor say about it", and this table is the only place that answer
exists.

    SELECT * FROM master_part_type_candidates WHERE master_part_id = 123;
"""
import dataclasses
import logging
import typing

from django.db import connection

from psycopg2 import extras as psycopg2_extras

from src import enums as src_enums
from src import models as src_models
from src.integrations.utils import product_type as pt

logger = logging.getLogger(__name__)

_LOG_PREFIX = "[PRODUCT-TYPE]"

BATCH_SIZE = 5000

STAGING_TABLE = "master_part_type_candidates"

# Rows whose provider_external_id is "<brand_id>_<key>" are split back apart here. The CASE
# guards the ::bigint cast -- a malformed id yields NULL and simply fails to join, rather than
# aborting the batch -- and MATERIALIZED forces that to happen before the join is attempted.
# Pagination reads from provider_parts alone so a batch where nothing joins still advances the
# cursor; filtering inside the paged CTE would stall the loop on the first such batch.
_COMPOSITE_BATCH_CTE = """
WITH batch AS MATERIALIZED (
    SELECT
        pp.id,
        pp.master_part_id,
        CASE WHEN pp.provider_external_id ~ '^[0-9]+_'
             THEN split_part(pp.provider_external_id, '_', 1)::bigint END AS raw_brand_id,
        CASE WHEN pp.provider_external_id ~ '^[0-9]+_'
             THEN substr(pp.provider_external_id, strpos(pp.provider_external_id, '_') + 1)
             END AS raw_key
    FROM provider_parts pp
    WHERE pp.provider_id = %(provider_id)s AND pp.id > %(last_id)s
    ORDER BY pp.id
    LIMIT %(limit)s
)
"""

_BARE_BATCH_CTE = """
WITH batch AS MATERIALIZED (
    SELECT pp.id, pp.master_part_id, pp.provider_external_id AS raw_key
    FROM provider_parts pp
    WHERE pp.provider_id = %(provider_id)s AND pp.id > %(last_id)s
    ORDER BY pp.id
    LIMIT %(limit)s
)
"""

# Same as above plus the master part's own brand, for sources whose provider_external_id is not
# unique in the raw table and need the brand to disambiguate. See _Source.brand_scope_sql.
_BARE_BATCH_CTE_WITH_BRAND = """
WITH batch AS MATERIALIZED (
    SELECT pp.id, pp.master_part_id, pp.provider_external_id AS raw_key, mp.brand_id
    FROM provider_parts pp
    JOIN master_parts mp ON mp.id = pp.master_part_id
    WHERE pp.provider_id = %(provider_id)s AND pp.id > %(last_id)s
    ORDER BY pp.id
    LIMIT %(limit)s
)
"""


@dataclasses.dataclass(frozen=True)
class _Source:
    """
    One distributor's contribution: how to reach its raw row from a ``ProviderPart``, which
    columns the rules need, and the rule to apply.

    ``composite_key`` is True for the ``"<brand_id>_<key>"`` provider_external_id shape every
    distributor uses except Turn14 (bare ``external_id``) and Meyer (bare ``meyer_part``).

    ``brand_scope_sql`` is an extra predicate for a source whose key is not unique in its own raw
    table, so the join would otherwise fan out and stage several contradictory candidates for one
    part. It may reference ``b.brand_id`` (the MasterPart's brand). Only Meyer needs it: 54,881
    ``meyer_part`` values exist under two MeyerBrands and 15,003 of those pairs disagree on
    ``sub_category``, and without scoping every one of them would be reported as a fake conflict.
    """
    name: str
    provider_kind: int
    raw_table: str
    raw_key_column: str
    select_columns: typing.Sequence[str]
    classify: typing.Callable[[typing.Dict, typing.Dict], typing.Optional[pt.Verdict]]
    composite_key: bool = True
    brand_scope_sql: typing.Optional[str] = None

    def batch_sql(self) -> str:
        if self.composite_key:
            cte = _COMPOSITE_BATCH_CTE
            join = "r.brand_id = b.raw_brand_id AND r.{} = b.raw_key".format(self.raw_key_column)
        else:
            cte = _BARE_BATCH_CTE_WITH_BRAND if self.brand_scope_sql else _BARE_BATCH_CTE
            join = "r.{} = b.raw_key".format(self.raw_key_column)
        if self.brand_scope_sql:
            join = "{} AND {}".format(join, self.brand_scope_sql)
        columns = ", ".join("r.{}".format(column) for column in self.select_columns)
        # An explicit join marker rather than "did every selected column come back NULL": a
        # Turn14 item with a NULL category is a real row we simply cannot classify, and must not
        # be reported as a failed join. The key column is NOT NULL in every source table.
        return (
            cte
            + "SELECT b.id, b.master_part_id, ({key} IS NOT NULL) AS joined, {columns}\n"
            "FROM batch b LEFT JOIN {table} r ON {join}\n"
            "ORDER BY b.id".format(
                key="r.{}".format(self.raw_key_column),
                columns=columns,
                table=self.raw_table,
                join=join,
            )
        )


# ------------------------------------------------------------------------------------------
# Per-source rule adapters. Each takes the raw row's selected columns plus a shared context
# (currently the PCdb terminology lookup) and defers to src.integrations.utils.product_type.
# ------------------------------------------------------------------------------------------

def _turn14(row, ctx):
    return pt.classify_turn14(row["category"])


def _wheelpros(row, ctx):
    return pt.classify_wheelpros(feed_type=row["feed_type"], size=row["size"])


def _vossen(row, ctx):
    return pt.classify_vossen(sku=row["sku"], diameter=row["diameter"])


def _elite_wheel_wheels(row, ctx):
    return pt.classify_elite_wheel(is_tire_sheet=False)


def _elite_wheel_tires(row, ctx):
    return pt.classify_elite_wheel(is_tire_sheet=True)


def _the_wheel_group(row, ctx):
    return pt.classify_the_wheel_group()


def _wps(row, ctx):
    return pt.classify_wps(row["product_type"])


def _rough_country(row, ctx):
    return pt.classify_rough_country(row["category"])


def _helmet_house(row, ctx):
    return pt.classify_helmet_house(row["category"])


def _tirerack(row, ctx):
    return pt.classify_tirerack_description(row["description"])


def _pcdb_verdict(terminology_text, ctx):
    """Resolve a distributor's terminology text against the PCdb mirror, then apply the rules."""
    hit = ctx["pcdb_by_name"].get(pt.normalize_terminology_name(terminology_text))
    if not hit:
        return None
    terminology_id, category_id = hit
    return pt.classify_pcdb_terminology(
        part_terminology_id=terminology_id, category_id=category_id
    )


def _premier(row, ctx):
    """
    Premier ships both a PCdb terminology name and a PCdb category name. Terminology is tried
    first because it is the only one of the two that can split "Tire and Wheel" into an actual
    wheel, an actual tire, and the lug nuts and caps filed beside them.
    """
    verdict = _pcdb_verdict(row["part_terminology"], ctx)
    if verdict is not None:
        return verdict
    return pt.classify_premier_category(row["part_category"])


def _meyer(row, ctx):
    """
    Meyer's ``sub_category`` is the PCdb terminology vocabulary uppercased, and can pack several
    terminologies into one semicolon-joined value ("WHEEL LUG NUT LOCK;WHEEL LOCK"). Every token
    is resolved; a value only produces a verdict when all of the tokens that resolve agree, so a
    row that is half wheel and half something else is left alone rather than taking the first.
    """
    verdicts = [_pcdb_verdict(token, ctx) for token in pt.split_multi_value(row["sub_category"])]
    resolved = {verdict.product_type for verdict in verdicts if verdict is not None}
    if len(resolved) == 1:
        product_type = resolved.pop()
        source = next(v.source for v in verdicts if v is not None and v.product_type == product_type)
        return pt.Verdict(product_type, source)
    if resolved:
        return None  # tokens disagree -- say nothing
    return pt.classify_meyer_category(row["category"])


SOURCES = (
    _Source(
        name="turn14",
        provider_kind=src_enums.BrandProviderKind.TURN_14.value,
        raw_table="turn14_items",
        raw_key_column="external_id",
        select_columns=("category",),
        classify=_turn14,
        composite_key=False,
    ),
    _Source(
        name="wheelpros",
        provider_kind=src_enums.BrandProviderKind.WHEELPROS.value,
        raw_table="wheelpros_parts",
        raw_key_column="part_number",
        select_columns=("feed_type", "size"),
        classify=_wheelpros,
    ),
    _Source(
        name="vossen",
        provider_kind=src_enums.BrandProviderKind.VOSSEN.value,
        raw_table="vossen_parts",
        raw_key_column="sku",
        select_columns=("sku", "diameter"),
        classify=_vossen,
    ),
    _Source(
        name="elite_wheel_wheels",
        provider_kind=src_enums.BrandProviderKind.ELITE_WHEEL.value,
        raw_table="elitewheels_part_wheels",
        raw_key_column="part_number",
        select_columns=("part_number",),
        classify=_elite_wheel_wheels,
    ),
    _Source(
        name="elite_wheel_tires",
        provider_kind=src_enums.BrandProviderKind.ELITE_WHEEL.value,
        raw_table="elitewheels_part_tires",
        raw_key_column="part_number",
        select_columns=("part_number",),
        classify=_elite_wheel_tires,
    ),
    _Source(
        name="the_wheel_group",
        provider_kind=src_enums.BrandProviderKind.THE_WHEEL_GROUP.value,
        raw_table="thewheelgroup_parts",
        raw_key_column="sku",
        select_columns=("sku",),
        classify=_the_wheel_group,
    ),
    _Source(
        name="wps",
        provider_kind=src_enums.BrandProviderKind.WESTERN_POWER_SPORTS.value,
        raw_table="wps_items",
        raw_key_column="sku",
        select_columns=("product_type",),
        classify=_wps,
    ),
    _Source(
        name="rough_country",
        provider_kind=src_enums.BrandProviderKind.ROUGH_COUNTRY.value,
        raw_table="rough_country_parts",
        raw_key_column="sku",
        select_columns=("category",),
        classify=_rough_country,
    ),
    _Source(
        name="helmet_house",
        provider_kind=src_enums.BrandProviderKind.HELMHOUSE.value,
        raw_table="helmet_house_parts",
        raw_key_column="sku",
        select_columns=("category",),
        classify=_helmet_house,
    ),
    _Source(
        name="tirerack",
        provider_kind=src_enums.BrandProviderKind.TIRERACK.value,
        raw_table="tirerack_parts",
        raw_key_column="part_number",
        select_columns=("description",),
        classify=_tirerack,
    ),
    _Source(
        name="premier",
        provider_kind=src_enums.BrandProviderKind.PREMIER_PERFORMANCE.value,
        raw_table="premier_parts",
        raw_key_column="premier_part_number",
        select_columns=("part_terminology", "part_category"),
        classify=_premier,
    ),
    _Source(
        name="meyer",
        provider_kind=src_enums.BrandProviderKind.MEYER.value,
        raw_table="meyer_parts",
        raw_key_column="meyer_part",
        select_columns=("sub_category", "category"),
        classify=_meyer,
        composite_key=False,
        brand_scope_sql=(
            "r.brand_id IN (SELECT m.meyer_brand_id FROM brand_meyer_brand_mapping m"
            " WHERE m.brand_id = b.brand_id)"
        ),
    ),
)

SOURCES_BY_NAME = {source.name: source for source in SOURCES}


def _load_pcdb_lookup() -> typing.Dict[str, typing.Tuple[int, typing.Optional[int]]]:
    """
    ``normalized terminology name -> (part_terminology_id, category_id)`` for the whole PCdb
    mirror (40,646 rows, small enough to hold). Aliases are included so a distributor using an
    accepted synonym still resolves; a name that is both a term and someone else's alias keeps
    the real term.
    """
    lookup: typing.Dict[str, typing.Tuple[int, typing.Optional[int]]] = {}
    rows = src_models.PcdbTerminologyFlat.objects.values(
        "part_terminology_id", "name", "category_id", "aliases"
    )
    for row in rows:
        for alias in row.get("aliases") or []:
            key = pt.normalize_terminology_name(alias)
            if key:
                lookup.setdefault(key, (row["part_terminology_id"], row["category_id"]))
    for row in rows:
        key = pt.normalize_terminology_name(row["name"])
        if key:
            lookup[key] = (row["part_terminology_id"], row["category_id"])
    return lookup


def _ensure_staging_table() -> None:
    with connection.cursor() as cursor:
        cursor.execute(
            "CREATE UNLOGGED TABLE IF NOT EXISTS {} ("
            "  master_part_id bigint NOT NULL,"
            "  provider_id integer NOT NULL,"
            "  source_name text NOT NULL,"
            "  product_type varchar(16) NOT NULL,"
            "  product_type_source varchar(64) NOT NULL,"
            "  tier smallint NOT NULL"
            ")".format(STAGING_TABLE)
        )
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS {t}_master_part_idx ON {t} (master_part_id)".format(
                t=STAGING_TABLE
            )
        )


def _clear_staging(source_names: typing.Sequence[str]) -> None:
    with connection.cursor() as cursor:
        cursor.execute(
            "DELETE FROM {} WHERE source_name = ANY(%s)".format(STAGING_TABLE), [list(source_names)]
        )


def collect_source(
    source: _Source,
    ctx: typing.Dict,
    limit: typing.Optional[int] = None,
) -> typing.Dict[str, int]:
    """
    Page one distributor's provider_parts, classify each, and stage the verdicts.

    Returns counts for the run report. ``scanned`` includes rows whose raw row did not join and
    rows the rules declined -- both are gaps worth seeing, and they are counted separately.
    """
    provider = src_models.Providers.objects.filter(kind=source.provider_kind).first()
    if not provider:
        logger.info("%s %s: no provider row, skipped.", _LOG_PREFIX, source.name)
        return {"scanned": 0, "unjoined": 0, "undecided": 0, "staged": 0}

    sql = source.batch_sql()
    stats = {"scanned": 0, "unjoined": 0, "undecided": 0, "staged": 0}
    last_id = 0
    while True:
        batch_limit = BATCH_SIZE
        if limit is not None:
            remaining = limit - stats["scanned"]
            if remaining <= 0:
                break
            batch_limit = min(BATCH_SIZE, remaining)

        with connection.cursor() as cursor:
            cursor.execute(
                sql,
                {"provider_id": provider.id, "last_id": last_id, "limit": batch_limit},
            )
            column_names = [column[0] for column in cursor.description]
            rows = cursor.fetchall()
        if not rows:
            break

        staged_rows = []
        for raw_row in rows:
            row = dict(zip(column_names, raw_row))
            last_id = max(last_id, row["id"])
            stats["scanned"] += 1
            if not row["joined"]:
                stats["unjoined"] += 1
                continue
            verdict = source.classify(row, ctx)
            if verdict is None:
                stats["undecided"] += 1
                continue
            staged_rows.append(
                (
                    row["master_part_id"],
                    provider.id,
                    source.name,
                    verdict.product_type,
                    verdict.source,
                    pt.tier_for_source(verdict.source),
                )
            )

        if staged_rows:
            # execute_values, not executemany: psycopg2's executemany issues one round trip per
            # row, and this stages ~2.7M of them.
            with connection.cursor() as cursor:
                psycopg2_extras.execute_values(
                    cursor,
                    "INSERT INTO {} (master_part_id, provider_id, source_name, product_type,"
                    " product_type_source, tier) VALUES %s".format(STAGING_TABLE),
                    staged_rows,
                    page_size=1000,
                )
            stats["staged"] += len(staged_rows)

        logger.info(
            "%s %s: scanned=%s staged=%s unjoined=%s undecided=%s (last_id=%s)",
            _LOG_PREFIX, source.name, stats["scanned"], stats["staged"],
            stats["unjoined"], stats["undecided"], last_id,
        )
        if len(rows) < batch_limit:
            break
    return stats


# Best tier wins; that tier must be unanimous. ``COUNT(DISTINCT product_type) = 1`` is the whole
# safety property -- a master part whose best-tier distributors disagree gets no value at all.
# Inner CTEs are named best_tier/resolved so that callers wrapping this as `WITH agreed AS (...)`
# do not shadow a name it uses itself. When distinct_types = 1 every row shares one product_type,
# so MIN(product_type_source) is just a deterministic pick among sources that already agree.
_RESOLVE_SELECT = """
WITH best_tier AS (
    SELECT master_part_id, MIN(tier) AS tier
    FROM {t}
    GROUP BY master_part_id
),
resolved AS (
    SELECT
        c.master_part_id,
        MIN(c.product_type) AS product_type,
        MIN(c.product_type_source) AS product_type_source,
        COUNT(DISTINCT c.product_type) AS distinct_types
    FROM {t} c
    JOIN best_tier b ON b.master_part_id = c.master_part_id AND b.tier = c.tier
    GROUP BY c.master_part_id
)
SELECT * FROM resolved
""".format(t=STAGING_TABLE)


def resolution_report() -> typing.Dict[str, typing.Any]:
    """Counts of what a resolve would write, without writing anything."""
    with connection.cursor() as cursor:
        cursor.execute(
            "WITH agreed AS ({}) "
            "SELECT product_type, COUNT(*) FILTER (WHERE distinct_types = 1), "
            "       COUNT(*) FILTER (WHERE distinct_types > 1) "
            "FROM agreed GROUP BY product_type ORDER BY 2 DESC".format(_RESOLVE_SELECT)
        )
        by_type = cursor.fetchall()
        cursor.execute(
            "WITH agreed AS ({}) SELECT COUNT(*) FROM agreed WHERE distinct_types > 1".format(
                _RESOLVE_SELECT
            )
        )
        conflicts = cursor.fetchone()[0]
        cursor.execute("SELECT COUNT(*) FROM master_parts")
        total_master = cursor.fetchone()[0]
    return {"by_type": by_type, "conflicts": conflicts, "total_master_parts": total_master}


def conflict_examples(limit: int = 20) -> typing.List[typing.Tuple]:
    """Master parts whose best-tier distributors disagree, with what each of them said."""
    with connection.cursor() as cursor:
        cursor.execute(
            "WITH agreed AS ({select}) "
            "SELECT c.master_part_id, b.name, mp.part_number, "
            "       string_agg(DISTINCT c.source_name || '=' || c.product_type, ', ') "
            "FROM agreed a "
            "JOIN {t} c ON c.master_part_id = a.master_part_id "
            "JOIN master_parts mp ON mp.id = a.master_part_id "
            "JOIN brands b ON b.id = mp.brand_id "
            "WHERE a.distinct_types > 1 "
            "GROUP BY 1, 2, 3 LIMIT %s".format(select=_RESOLVE_SELECT, t=STAGING_TABLE),
            [limit],
        )
        return cursor.fetchall()


def apply_resolution() -> int:
    """
    Write the unanimous best-tier verdicts onto ``master_parts``. Returns rows updated.

    Only touches rows whose value actually changes, so a re-run after no rule change is a no-op
    and does not churn ``updated_at`` across 1.5M rows.
    """
    with connection.cursor() as cursor:
        cursor.execute(
            "WITH agreed AS ({select}) "
            "UPDATE master_parts mp "
            "SET product_type = a.product_type, product_type_source = a.product_type_source "
            "FROM agreed a "
            "WHERE a.master_part_id = mp.id AND a.distinct_types = 1 "
            "  AND (mp.product_type IS DISTINCT FROM a.product_type "
            "   OR mp.product_type_source IS DISTINCT FROM a.product_type_source)".format(
                select=_RESOLVE_SELECT
            )
        )
        return cursor.rowcount


def gap_report(limit: int = 15) -> typing.Dict[str, typing.Any]:
    """Where the unclassified parts are, by brand and by which distributors carry them."""
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT COUNT(*) FROM master_parts WHERE product_type IS NULL"
        )
        unclassified = cursor.fetchone()[0]
        cursor.execute(
            "SELECT b.name, COUNT(*) AS n FROM master_parts mp "
            "JOIN brands b ON b.id = mp.brand_id "
            "WHERE mp.product_type IS NULL GROUP BY 1 ORDER BY 2 DESC LIMIT %s",
            [limit],
        )
        by_brand = cursor.fetchall()
        cursor.execute(
            "SELECT p.name, COUNT(DISTINCT mp.id) AS n FROM master_parts mp "
            "JOIN provider_parts pp ON pp.master_part_id = mp.id "
            "JOIN providers p ON p.id = pp.provider_id "
            "WHERE mp.product_type IS NULL GROUP BY 1 ORDER BY 2 DESC LIMIT %s",
            [limit],
        )
        by_provider = cursor.fetchall()
    return {"unclassified": unclassified, "by_brand": by_brand, "by_provider": by_provider}


def run(
    source_names: typing.Optional[typing.Sequence[str]] = None,
    limit_per_source: typing.Optional[int] = None,
    apply_changes: bool = False,
) -> typing.Dict[str, typing.Any]:
    """
    Collect verdicts for the named sources (default: all), then report -- and only write when
    ``apply_changes`` is True. The collect phase always runs: it only touches the staging table,
    and having it populated is what makes the dry-run report real rather than an estimate.
    """
    selected = [SOURCES_BY_NAME[name] for name in (source_names or list(SOURCES_BY_NAME))]
    _ensure_staging_table()
    _clear_staging([source.name for source in selected])

    ctx = {"pcdb_by_name": _load_pcdb_lookup()}
    logger.info("%s PCdb terminology lookup: %s names.", _LOG_PREFIX, len(ctx["pcdb_by_name"]))

    per_source = {}
    for source in selected:
        per_source[source.name] = collect_source(source, ctx, limit=limit_per_source)

    result = {
        "per_source": per_source,
        "resolution": resolution_report(),
        "conflicts": conflict_examples(),
        "applied": None,
    }
    if apply_changes:
        result["applied"] = apply_resolution()
        result["gaps"] = gap_report()
    return result
