# Generated by Django 4.1.7 on 2025-12-10 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyDestinations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.PositiveSmallIntegerField()),
                ("status_name", models.CharField(max_length=255)),
                ("destination_type", models.PositiveSmallIntegerField()),
                ("destination_type_name", models.CharField(max_length=255)),
                ("credentials", models.JSONField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinations",
                        to="src.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_destinations",
            },
        ),
    ]
