# Generated by Django 4.1.7 on 2025-12-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0003_companydestinations_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brands",
            name="data",
            field=models.JSONField(null=True),
        ),
    ]
