# Generated by Django 4.1.7 on 2025-12-10 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0004_brands_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyDestinationParts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_data", models.JSONField()),
                ("source_external_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="src.brands",
                    ),
                ),
                (
                    "company_destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="src.companydestinations",
                    ),
                ),
            ],
            options={
                "db_table": "company_destination_parts",
            },
        ),
        migrations.CreateModel(
            name="CompanyDestinationPartsHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="src.companydestinationparts",
                    ),
                ),
            ],
            options={
                "db_table": "company_destination_parts_history",
            },
        ),
        migrations.CreateModel(
            name="CompanyDestinationPartsPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferences", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts_preferences",
                        to="src.companydestinations",
                    ),
                ),
            ],
            options={
                "db_table": "company_destination_parts_preferences",
                "unique_together": {("company_destination",)},
            },
        ),
    ]
