# Generated by Django 4.1.7 on 2025-12-11 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0006_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profiles",
                to="src.company",
            ),
        ),
    ]
