# Generated by Django 4.1.7 on 2025-12-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0007_alter_userprofile_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydestinations",
            name="primary",
            field=models.BooleanField(default=False),
        ),
    ]
