# Generated by Django 4.1.7 on 2025-12-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0008_companydestinations_primary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Turn14Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("dropship", models.BooleanField(default=False)),
                ("price_groups", models.JSONField(null=True)),
                ("logo", models.TextField(null=True)),
                ("aaia_code", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "turn14_brands",
                "unique_together": {("external_id",)},
            },
        ),
    ]
