# Generated by Django 4.1.7 on 2025-12-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0009_turn14brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="providers",
            name="primary",
            field=models.BooleanField(default=False),
        ),
    ]
