# Generated by Django 4.1.7 on 2025-12-12 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0010_providers_primary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companydestinations",
            name="primary",
        ),
    ]
