# Generated by Django 4.1.7 on 2025-12-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0011_remove_companydestinations_primary"),
    ]

    operations = [
        migrations.AddField(
            model_name="providers",
            name="kind",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="providers",
            name="kind_name",
            field=models.CharField(default="TURN_14", max_length=255),
            preserve_default=False,
        ),
    ]
