# Generated by Django 4.1.7 on 2025-12-12 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0012_providers_kind_providers_kind_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="providers",
            unique_together={("kind",)},
        ),
        migrations.RemoveField(
            model_name="providers",
            name="primary",
        ),
        migrations.CreateModel(
            name="CompanyProviders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credentials", models.JSONField()),
                ("primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_providers",
                        to="src.company",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_providers",
                        to="src.providers",
                    ),
                ),
            ],
            options={
                "db_table": "company_providers",
                "unique_together": {("company", "provider")},
            },
        ),
    ]
