# Generated by Django 4.1.7 on 2025-12-12 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0013_alter_providers_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyBrands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brands",
                        to="src.brands",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brands",
                        to="src.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_brands",
                "unique_together": {("company", "brand")},
            },
        ),
    ]
