# Generated by Django 4.1.7 on 2025-12-12 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0014_companybrands"),
    ]

    operations = [
        migrations.CreateModel(
            name="Turn14BrandToBrandMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_brands",
                        to="src.brands",
                    ),
                ),
                (
                    "turn_14_brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_brand_mapping",
                        to="src.turn14brand",
                    ),
                ),
            ],
            options={
                "db_table": "turn14_brand_to_brand_mapping",
                "unique_together": {("turn_14_brand", "brand")},
            },
        ),
    ]
