# Generated by Django 4.1.7 on 2025-12-12 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0015_turn14brandtobrandmapping"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Turn14BrandToBrandMapping",
        ),
    ]
