# Generated by Django 4.1.7 on 2025-12-12 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0016_delete_turn14brandtobrandmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="Turn14Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("product_name", models.CharField(max_length=255, null=True)),
                ("part_number", models.CharField(max_length=255, null=True)),
                ("mfr_part_number", models.CharField(max_length=255, null=True)),
                ("part_description", models.TextField(null=True)),
                ("category", models.CharField(max_length=255, null=True)),
                ("subcategory", models.CharField(max_length=255, null=True)),
                ("external_brand_id", models.IntegerField(null=True)),
                ("brand_name", models.CharField(max_length=255, null=True)),
                ("price_group_id", models.IntegerField(null=True)),
                ("price_group", models.CharField(max_length=255, null=True)),
                ("active", models.BooleanField(default=False)),
                ("born_on_date", models.DateField(null=True)),
                ("regular_stock", models.BooleanField(default=False)),
                ("powersports_indicator", models.BooleanField(default=False)),
                ("dropship_controller_id", models.IntegerField(null=True)),
                ("air_freight_prohibited", models.BooleanField(default=False)),
                ("not_carb_approved", models.BooleanField(default=False)),
                ("carb_acknowledgement_required", models.BooleanField(default=False)),
                ("ltl_freight_required", models.BooleanField(default=False)),
                ("prop_65", models.CharField(max_length=255, null=True)),
                ("epa", models.CharField(max_length=255, null=True)),
                ("units_per_sku", models.IntegerField(null=True)),
                ("clearance_item", models.BooleanField(default=False)),
                ("thumbnail", models.TextField(null=True)),
                ("barcode", models.CharField(max_length=255, null=True)),
                ("dimensions", models.JSONField(null=True)),
                ("warehouse_availability", models.JSONField(null=True)),
                ("source_data", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="src.turn14brand",
                    ),
                ),
            ],
            options={
                "db_table": "turn14_items",
                "unique_together": {("external_id",)},
            },
        ),
        migrations.CreateModel(
            name="BrandTurn14BrandMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turn14_brand_mappings",
                        to="src.brands",
                    ),
                ),
                (
                    "turn14_brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_mappings",
                        to="src.turn14brand",
                    ),
                ),
            ],
            options={
                "db_table": "brand_turn14_brand_mapping",
                "unique_together": {("brand", "turn14_brand")},
            },
        ),
    ]
