# Generated by Django 4.1.7 on 2025-12-12 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0017_turn14items_brandturn14brandmapping"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="turn14items",
            name="source_data",
        ),
        migrations.CreateModel(
            name="Turn14BrandData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255, null=True)),
                ("files", models.JSONField(null=True)),
                ("descriptions", models.JSONField(null=True)),
                ("relationships", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_data",
                        to="src.turn14brand",
                    ),
                ),
            ],
            options={
                "db_table": "turn14_brand_data",
                "unique_together": {("external_id",)},
            },
        ),
    ]
