# Generated by Django 4.1.7 on 2025-12-12 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0018_remove_turn14items_source_data_turn14branddata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Turn14BrandPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255, null=True)),
                (
                    "purchase_cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("has_map", models.BooleanField(default=False)),
                ("can_purchase", models.BooleanField(default=False)),
                ("pricelists", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_pricing",
                        to="src.turn14brand",
                    ),
                ),
            ],
            options={
                "db_table": "turn14_brand_pricing",
                "unique_together": {("external_id",)},
            },
        ),
    ]
