# Generated by Django 4.1.7 on 2025-12-12 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0019_turn14brandpricing"),
    ]

    operations = [
        migrations.CreateModel(
            name="Turn14BrandInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255, null=True)),
                ("inventory", models.JSONField(null=True)),
                ("manufacturer", models.JSONField(null=True)),
                ("relationships", models.JSONField(null=True)),
                ("total_inventory", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_inventory",
                        to="src.turn14brand",
                    ),
                ),
            ],
            options={
                "db_table": "turn14_brand_inventory",
                "unique_together": {("external_id",)},
            },
        ),
    ]
