# Generated by Django 4.1.7 on 2025-12-12 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0020_turn14brandinventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="turn14brandinventory",
            name="eta",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="turn14brandinventory",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand_inventory",
                to="src.turn14brand",
            ),
        ),
    ]
