# Generated by Django 4.1.7 on 2025-12-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0021_turn14brandinventory_eta_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BigCommerceParts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("sku", models.TextField(max_length=255)),
                ("raw_data", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "bigcommerce_parts",
                "unique_together": {("external_id", "sku")},
            },
        ),
    ]
