# Generated by Django 4.1.7 on 2025-12-15 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0022_bigcommerceparts"),
    ]

    operations = [
        migrations.CreateModel(
            name="BigCommerceBrands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("name", models.TextField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_name",
                        to="src.brands",
                    ),
                ),
            ],
            options={
                "db_table": "bigcommerce_brands",
                "unique_together": {("external_id", "brand")},
            },
        ),
    ]
