# Generated by Django 4.1.7 on 2025-12-15 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0023_bigcommercebrands"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bigcommercebrands",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="bigcommerceparts",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="bigcommercebrands",
            name="company_destination",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bigcommerce_brands",
                to="src.companydestinations",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bigcommerceparts",
            name="company_destination",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bigcommerce_parts",
                to="src.companydestinations",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bigcommercebrands",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bigcommerce_brands",
                to="src.brands",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bigcommercebrands",
            unique_together={("external_id", "brand", "company_destination")},
        ),
        migrations.AlterUniqueTogether(
            name="bigcommerceparts",
            unique_together={("external_id", "sku", "company_destination")},
        ),
    ]
