# Generated by Django 4.1.7 on 2025-12-15 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0024_alter_bigcommercebrands_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bigcommerceparts",
            name="external_brand_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="companybrands",
            name="status",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companybrands",
            name="status_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="CompanyBrandDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinations",
                        to="src.companybrands",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_brands",
                        to="src.companydestinations",
                    ),
                ),
            ],
            options={
                "db_table": "company_brand_destination",
                "unique_together": {("company_brand", "destination")},
            },
        ),
    ]
