# Generated by Django 4.1.7 on 2025-12-16 08:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0025_bigcommerceparts_external_brand_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companydestinationparts",
            old_name="brand_id",
            new_name="brand",
        ),
    ]
