# Generated by Django 4.1.7 on 2025-12-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0026_rename_brand_id_companydestinationparts_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydestinationparts",
            name="destination_data",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companydestinationparts",
            name="destination_external_id",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="companydestinationparts",
            name="part_unique_key",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="companydestinationparts",
            name="source_external_id",
            field=models.TextField(),
        ),
    ]
