# Generated by Django 4.1.7 on 2025-12-16 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0027_companydestinationparts_destination_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydestinationpartshistory",
            name="changes",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="companydestinationpartshistory",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="companydestinationparts",
            name="destination_data",
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name="CompanyDestinationExecutionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.PositiveSmallIntegerField()),
                ("status_name", models.CharField(max_length=255)),
                ("products_processed", models.IntegerField(default=0)),
                ("products_created", models.IntegerField(default=0)),
                ("products_updated", models.IntegerField(default=0)),
                ("products_failed", models.IntegerField(default=0)),
                ("error_message", models.TextField(null=True)),
                ("message", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(null=True)),
                (
                    "company_brand_destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_runs",
                        to="src.companybranddestination",
                    ),
                ),
            ],
            options={
                "db_table": "company_destination_execution_run",
            },
        ),
        migrations.AddField(
            model_name="companydestinationpartshistory",
            name="execution_run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_records",
                to="src.companydestinationexecutionrun",
            ),
        ),
    ]
