# Generated by Django 4.1.7 on 2025-12-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0028_companydestinationpartshistory_changes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SDCBrands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("name", models.TextField(max_length=255)),
                ("aaia_code", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sdc_brands",
                "unique_together": {("external_id", "name")},
            },
        ),
    ]
