# Generated by Django 4.1.7 on 2025-12-19 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0029_sdcbrands"),
    ]

    operations = [
        migrations.CreateModel(
            name="SDCPartFitment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.TextField(max_length=255)),
                ("year", models.IntegerField()),
                ("make", models.TextField(max_length=255)),
                ("model", models.TextField(max_length=255)),
                (
                    "brand_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fitment_brands",
                        to="src.sdcbrands",
                    ),
                ),
            ],
            options={
                "db_table": "sdc_part_fitment",
                "unique_together": {("sku", "brand_id", "year", "make", "model")},
            },
        ),
    ]
