# Generated by Django 4.1.7 on 2025-12-19 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0030_sdcpartfitment"),
    ]

    operations = [
        migrations.CreateModel(
            name="SDCParts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_number", models.CharField(max_length=255)),
                ("brand_label", models.CharField(max_length=255, null=True)),
                ("gtin", models.CharField(max_length=255, null=True)),
                ("category_pcdb", models.CharField(max_length=255, null=True)),
                ("life_cycle_status", models.CharField(max_length=255, null=True)),
                ("country_of_origin", models.CharField(max_length=255, null=True)),
                ("warranty", models.TextField(null=True)),
                ("long_description", models.TextField(null=True)),
                ("extended_description", models.TextField(null=True)),
                ("application_summary", models.TextField(null=True)),
                ("features_and_benefits", models.TextField(null=True)),
                ("marketing_description", models.TextField(null=True)),
                ("title", models.CharField(max_length=255, null=True)),
                ("keywords", models.TextField(null=True)),
                ("product_attributes", models.TextField(null=True)),
                (
                    "jobber_usd",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "retail_usd",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "map_usd",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "unilateral_usd",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("primary_image", models.TextField(null=True)),
                ("additional_image", models.TextField(null=True)),
                ("installation_instructions", models.TextField(null=True)),
                ("logo", models.TextField(null=True)),
                ("video_random", models.TextField(null=True)),
                ("video_installation", models.TextField(null=True)),
                (
                    "length_for_case",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "width_for_case",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "height_for_case",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "weight_for_case",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("inventory", models.IntegerField(null=True)),
                ("external_brand_id", models.CharField(max_length=255, null=True)),
                ("part_terminology_label", models.CharField(max_length=255, null=True)),
                (
                    "quantity_per_application",
                    models.CharField(max_length=255, null=True),
                ),
                ("hazardous_material", models.CharField(max_length=255, null=True)),
                ("condition", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="src.sdcbrands",
                    ),
                ),
            ],
            options={
                "db_table": "sdc_parts",
                "unique_together": {("part_number", "brand")},
            },
        ),
        migrations.CreateModel(
            name="BrandSDCBrandMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sdc_brand_mappings",
                        to="src.brands",
                    ),
                ),
                (
                    "sdc_brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_mappings",
                        to="src.sdcbrands",
                    ),
                ),
            ],
            options={
                "db_table": "brand_sdc_brand_mapping",
                "unique_together": {("brand", "sdc_brand")},
            },
        ),
    ]
