# Generated by Django 4.1.7 on 2025-12-19 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0031_sdcparts_brandsdcbrandmapping"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sdcpartfitment",
            old_name="brand_id",
            new_name="brand",
        ),
    ]
