# Generated by Django 4.1.7 on 2025-12-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0032_rename_brand_id_sdcpartfitment_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="sdcpartfitment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sdcpartfitment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
