# Generated by Django 4.1.7 on 2025-12-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0033_sdcpartfitment_created_at_sdcpartfitment_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="sdcpartfitment",
            name="category_pcdb",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sdcpartfitment",
            name="subcategory_pcdb",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
