# Generated by Django 4.1.7 on 2025-12-22 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0034_sdcpartfitment_category_pcdb_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BigCommerceCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("parent_id", models.IntegerField(default=0)),
                ("tree_id", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bigcommerce_categories",
                        to="src.companydestinations",
                    ),
                ),
            ],
            options={
                "db_table": "bigcommerce_categories",
                "unique_together": {("external_id", "company_destination", "tree_id")},
            },
        ),
    ]
