# Generated by Django 4.1.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0035_bigcommercecategories"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeystoneBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("aaia_code", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "keystone_brands",
                "unique_together": {("external_id",)},
            },
        ),
        migrations.CreateModel(
            name="BrandKeystoneBrandMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keystone_brand_mappings",
                        to="src.brands",
                    ),
                ),
                (
                    "keystone_brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_mappings",
                        to="src.keystonebrand",
                    ),
                ),
            ],
            options={
                "db_table": "brand_keystone_brand_mapping",
                "unique_together": {("brand", "keystone_brand")},
            },
        ),
        migrations.CreateModel(
            name="KeystoneParts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vcpn", models.CharField(max_length=255)),
                ("vendor_code", models.CharField(max_length=255, null=True)),
                ("part_number", models.CharField(max_length=255, null=True)),
                ("manufacturer_part_no", models.CharField(max_length=255, null=True)),
                ("long_description", models.TextField(null=True)),
                (
                    "jobber_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("upsable", models.BooleanField(default=False)),
                (
                    "core_charge",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("case_qty", models.IntegerField(null=True)),
                ("is_non_returnable", models.BooleanField(default=False)),
                ("prop65_toxicity", models.CharField(max_length=255, null=True)),
                ("upc_code", models.CharField(max_length=255, null=True)),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "height",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "length",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "width",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("aaia_code", models.CharField(max_length=255, null=True)),
                ("is_hazmat", models.BooleanField(default=False)),
                ("is_chemical", models.BooleanField(default=False)),
                (
                    "ups_ground_assessorial",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "us_ltl",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("east_qty", models.IntegerField(null=True)),
                ("midwest_qty", models.IntegerField(null=True)),
                ("california_qty", models.IntegerField(null=True)),
                ("southeast_qty", models.IntegerField(null=True)),
                ("pacific_nw_qty", models.IntegerField(null=True)),
                ("texas_qty", models.IntegerField(null=True)),
                ("great_lakes_qty", models.IntegerField(null=True)),
                ("florida_qty", models.IntegerField(null=True)),
                ("total_qty", models.IntegerField(null=True)),
                ("kit_components", models.TextField(null=True)),
                ("is_kit", models.BooleanField(default=False)),
                ("raw_data", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="src.keystonebrand",
                    ),
                ),
            ],
            options={
                "db_table": "keystone_parts",
                "unique_together": {("vcpn", "brand")},
            },
        ),
    ]
