# Generated by Django 4.1.7

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0036_keystonebrand_keystoneparts_brandkeystonebrandmapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="brands",
            name="aaia_code",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
