# Generated by Django 4.1.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0037_brands_aaia_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_number", models.CharField(max_length=255)),
                ("sku", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(null=True)),
                ("aaia_code", models.CharField(max_length=255, null=True)),
                ("image_url", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="master_parts",
                        to="src.brands",
                    ),
                ),
            ],
            options={
                "db_table": "master_parts",
                "unique_together": {("brand", "part_number")},
            },
        ),
        migrations.CreateModel(
            name="ProviderPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_external_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "master_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_parts",
                        to="src.masterpart",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_parts",
                        to="src.providers",
                    ),
                ),
            ],
            options={
                "db_table": "provider_parts",
                "unique_together": {("master_part", "provider")},
            },
        ),
        migrations.CreateModel(
            name="ProviderPartInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_qty", models.IntegerField(default=0)),
                ("manufacturer_inventory", models.IntegerField(null=True)),
                ("warehouse_availability", models.JSONField(null=True)),
                ("last_synced_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider_part",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="src.providerpart",
                    ),
                ),
            ],
            options={
                "db_table": "provider_part_inventory",
            },
        ),
        migrations.CreateModel(
            name="ProviderPartCompanyPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "jobber_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "map_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "msrp",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("last_synced_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_part_pricing",
                        to="src.company",
                    ),
                ),
                (
                    "provider_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_pricing",
                        to="src.providerpart",
                    ),
                ),
            ],
            options={
                "db_table": "provider_part_company_pricing",
                "unique_together": {("provider_part", "company")},
            },
        ),
    ]
