# Generated by Django 4.1.7

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0038_masterpart_providerpart_providerpartinventory_providerpartcompanypricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerpartinventory",
            name="manufacturer_esd",
            field=models.DateField(null=True),
        ),
        migrations.RenameField(
            model_name="providerpartinventory",
            old_name="total_qty",
            new_name="warehouse_total_qty",
        ),
    ]
