# Generated by Django 4.1.7

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0039_providerpartinventory_manufacturer_esd"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerpartcompanypricing",
            name="retail_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
