# Generated by Django 4.1.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0041_company_onboarding_companyonboardingpreferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_company_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profiles",
                to="src.company",
            ),
        ),
    ]
