# Generated by Django 4.1.7

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0043_turn14location"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledTaskExecution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("status", models.PositiveSmallIntegerField()),
                ("status_name", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "scheduled_task_execution",
                "ordering": ["-created_at"],
            },
        ),
    ]
