# Generated by Django 4.1.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0045_partrequestaudit"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoughCountryBrand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("aaia_code", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rough_country_brands",
                "unique_together": {("external_id",)},
            },
        ),
        migrations.CreateModel(
            name="RoughCountryPart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sku", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, max_length=512, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("sale_price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("cost", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("availability", models.CharField(blank=True, max_length=255, null=True)),
                ("nv_stock", models.IntegerField(blank=True, null=True)),
                ("tn_stock", models.IntegerField(blank=True, null=True)),
                ("link", models.TextField(blank=True, null=True)),
                ("image_1", models.TextField(blank=True, null=True)),
                ("image_2", models.TextField(blank=True, null=True)),
                ("image_3", models.TextField(blank=True, null=True)),
                ("image_4", models.TextField(blank=True, null=True)),
                ("image_5", models.TextField(blank=True, null=True)),
                ("image_6", models.TextField(blank=True, null=True)),
                ("video", models.TextField(blank=True, null=True)),
                ("features", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("manufacturer", models.CharField(blank=True, max_length=255, null=True)),
                ("upc", models.CharField(blank=True, max_length=255, null=True)),
                ("weight", models.CharField(blank=True, max_length=64, null=True)),
                ("height", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("width", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("length", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("added_date", models.DateField(blank=True, null=True)),
                ("is_discontinued", models.BooleanField(default=False)),
                ("discontinued_date", models.DateTimeField(blank=True, null=True)),
                ("replacement_sku", models.CharField(blank=True, max_length=255, null=True)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="src.roughcountrybrand",
                    ),
                ),
            ],
            options={
                "db_table": "rough_country_parts",
                "unique_together": {("brand", "sku")},
            },
        ),
        migrations.CreateModel(
            name="RoughCountryFitment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_year", models.IntegerField(blank=True, null=True)),
                ("end_year", models.IntegerField(blank=True, null=True)),
                ("make", models.CharField(blank=True, max_length=128, null=True)),
                ("model", models.CharField(blank=True, max_length=128, null=True)),
                ("submodel", models.CharField(blank=True, max_length=255, null=True)),
                ("drive", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fitments",
                        to="src.roughcountrypart",
                    ),
                ),
            ],
            options={
                "db_table": "rough_country_fitment",
                "unique_together": {("part", "start_year", "end_year", "make", "model", "submodel", "drive")},
            },
        ),
        migrations.CreateModel(
            name="BrandRoughCountryBrandMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rough_country_brand_mappings",
                        to="src.brands",
                    ),
                ),
                (
                    "rough_country_brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_mappings",
                        to="src.roughcountrybrand",
                    ),
                ),
            ],
            options={
                "db_table": "brand_rough_country_brand_mapping",
                "unique_together": {("brand", "rough_country_brand")},
            },
        ),
    ]
