# Generated by Django 4.1.7

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0046_roughcountrybrand_roughcountrypart_roughcountryfitment_brandroughcountrybrandmapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="roughcountrypart",
            name="cnd_map",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="roughcountrypart",
            name="cnd_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
