# Generated by Django 4.1.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0047_roughcountrypart_cnd_map_cnd_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="WheelProsBrand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wheelpros_brands",
                "unique_together": {("external_id",)},
            },
        ),
        migrations.CreateModel(
            name="WheelProsPart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("part_number", models.CharField(max_length=255)),
                ("part_description", models.TextField(blank=True, null=True)),
                ("display_style_no", models.CharField(blank=True, max_length=255, null=True)),
                ("finish", models.CharField(blank=True, max_length=255, null=True)),
                ("size", models.CharField(blank=True, max_length=255, null=True)),
                ("bolt_pattern", models.CharField(blank=True, max_length=255, null=True)),
                ("offset", models.CharField(blank=True, max_length=255, null=True)),
                ("center_bore", models.CharField(blank=True, max_length=255, null=True)),
                ("load_rating", models.CharField(blank=True, max_length=255, null=True)),
                ("shipping_weight", models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ("image_url", models.TextField(blank=True, null=True)),
                ("inv_order_type", models.CharField(blank=True, max_length=255, null=True)),
                ("style", models.CharField(blank=True, max_length=255, null=True)),
                ("total_qoh", models.IntegerField(blank=True, null=True)),
                ("msrp_usd", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("map_usd", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("run_date", models.DateTimeField(blank=True, null=True)),
                ("warehouse_availability", models.JSONField(blank=True, null=True)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="src.wheelprosbrand",
                    ),
                ),
            ],
            options={
                "db_table": "wheelpros_parts",
                "unique_together": {("brand", "part_number")},
            },
        ),
        migrations.CreateModel(
            name="BrandWheelProsBrandMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wheelpros_brand_mappings",
                        to="src.brands",
                    ),
                ),
                (
                    "wheelpros_brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_mappings",
                        to="src.wheelprosbrand",
                    ),
                ),
            ],
            options={
                "db_table": "brand_wheelpros_brand_mapping",
                "unique_together": {("brand", "wheelpros_brand")},
            },
        ),
    ]
