# Generated by Django 4.1.7

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0047_roughcountrypart_cnd_map_cnd_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
