# Generated by Django 4.1.7

from django.db import migrations


def create_wheelpros_provider(apps, schema_editor):
    Providers = apps.get_model("src", "Providers")
    Providers.objects.get_or_create(
        kind=5,
        defaults={
            "name": "WheelPros",
            "status": 1,
            "status_name": "ACTIVE",
            "type": 2,
            "type_name": "DISTRIBUTOR",
            "kind_name": "WHEELPROS",
        },
    )


def remove_wheelpros_provider(apps, schema_editor):
    Providers = apps.get_model("src", "Providers")
    Providers.objects.filter(kind=5).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0048_wheelprosbrand_brandwheelprosbrandmapping_wheelprospart"),
    ]

    operations = [
        migrations.RunPython(create_wheelpros_provider, remove_wheelpros_provider),
    ]
