# Generated by Django 4.1.7

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0049_seed_wheelpros_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="wheelprospart",
            name="sku",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wheelprospart",
            name="manufacturer_part_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
