# Generated by Django 4.1.7

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0050_wheelprospart_sku_manufacturer_part_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wheelprospart",
            name="sku",
        ),
    ]
