# Generated by Django 4.1.7 on 2026-03-19 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0048_company_stripe_customer_id"),
        ("src", "0050_wheelprospart_sku_manufacturer_part_number"),
    ]

    operations = []
