# Generated by Django 4.1.7 on 2026-03-19 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0051_merge_20260319_1002"),
        ("src", "0051_remove_wheelprospart_sku"),
    ]

    operations = []
