# Generated by Django 4.1.7

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0051_remove_wheelprospart_sku"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wheelprospart",
            name="manufacturer_part_number",
        ),
    ]
