# Generated by Django 4.1.7

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0052_remove_wheelprospart_manufacturer_part_number"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="masterpart",
            index=models.Index(fields=["brand", "sku"], name="master_parts_brand_sku_idx"),
        ),
    ]
