# Generated by Django 4.1.7 on 2026-03-19 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0052_merge_20260319_1013"),
        ("src", "0052_remove_wheelprospart_manufacturer_part_number"),
    ]

    operations = []
