# Generated by Django 4.1.7 on 2026-03-19 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0053_masterpart_brand_sku_idx"),
        ("src", "0053_merge_20260319_1023"),
    ]

    operations = []
