# Generated by Django 4.1.7

from django.db import migrations, models
import django.db.models.deletion


def create_meyer_provider(apps, schema_editor):
    Providers = apps.get_model("src", "Providers")
    Providers.objects.get_or_create(
        kind=6,
        defaults={
            "name": "Meyer",
            "status": 1,
            "status_name": "ACTIVE",
            "type": 2,
            "type_name": "DISTRIBUTOR",
            "kind_name": "MEYER",
        },
    )


def remove_meyer_provider(apps, schema_editor):
    Providers = apps.get_model("src", "Providers")
    Providers.objects.filter(kind=6).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0054_merge_20260319_1049"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeyerBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=512)),
                ("name", models.CharField(max_length=512)),
                (
                    "aaia_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "meyer_brands",
                "unique_together": {("external_id",)},
            },
        ),
        migrations.CreateModel(
            name="BrandMeyerBrandMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meyer_brand_mappings",
                        to="src.brands",
                    ),
                ),
                (
                    "meyer_brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_mappings",
                        to="src.meyerbrand",
                    ),
                ),
            ],
            options={
                "db_table": "brand_meyer_brand_mapping",
                "unique_together": {("brand", "meyer_brand")},
            },
        ),
        migrations.CreateModel(
            name="MeyerParts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meyer_part", models.CharField(max_length=255)),
                (
                    "mfg_item_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "jobber_price",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=14, null=True
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=14, null=True
                    ),
                ),
                (
                    "core_charge",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=14, null=True
                    ),
                ),
                ("upc", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "map_price",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=14, null=True
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sub_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_ltl", models.BooleanField(default=False)),
                ("is_discontinued", models.BooleanField(default=False)),
                ("is_oversize", models.BooleanField(default=False)),
                ("addtl_handling_charge", models.BooleanField(default=False)),
                (
                    "available_qty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "mfg_qty_available",
                    models.IntegerField(blank=True, null=True),
                ),
                ("inventory_ltl", models.IntegerField(blank=True, null=True)),
                ("is_stocking", models.BooleanField(default=False)),
                ("is_special_order", models.BooleanField(default=False)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="src.meyerbrand",
                    ),
                ),
            ],
            options={
                "db_table": "meyer_parts",
                "unique_together": {("meyer_part", "brand")},
            },
        ),
        migrations.RunPython(create_meyer_provider, remove_meyer_provider),
    ]
