# Generated by Django 4.1.7

from django.db import migrations, models
import django.db.models.deletion


def backfill_turn14_brand_pricing_company(apps, schema_editor):
    Turn14BrandPricing = apps.get_model("src", "Turn14BrandPricing")
    CompanyProviders = apps.get_model("src", "CompanyProviders")
    Company = apps.get_model("src", "Company")

    cp = (
        CompanyProviders.objects.filter(
            provider__kind=1,
            provider__status=1,
            primary=True,
        )
        .order_by("id")
        .first()
    )
    if not cp:
        cp = (
            CompanyProviders.objects.filter(
                provider__kind=1,
                provider__status=1,
            )
            .order_by("id")
            .first()
        )

    if cp:
        Turn14BrandPricing.objects.filter(company__isnull=True).update(company_id=cp.company_id)

    fallback = Company.objects.order_by("id").first()
    if fallback:
        Turn14BrandPricing.objects.filter(company__isnull=True).update(company_id=fallback.id)


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0055_meyer_provider"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="turn14brandpricing",
            unique_together=(),
        ),
        migrations.AddField(
            model_name="turn14brandpricing",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turn14_brand_pricing",
                to="src.company",
            ),
        ),
        migrations.RunPython(backfill_turn14_brand_pricing_company, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="turn14brandpricing",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turn14_brand_pricing",
                to="src.company",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="turn14brandpricing",
            unique_together={("company", "external_id")},
        ),
    ]
