# Generated by Django 4.1.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0056_turn14brandpricing_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeystoneCompanyPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobber_price", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("core_charge", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keystone_company_pricing",
                        to="src.company",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_pricing",
                        to="src.keystoneparts",
                    ),
                ),
            ],
            options={
                "db_table": "keystone_company_pricing",
                "unique_together": {("part", "company")},
            },
        ),
    ]
