# Generated by Django 4.1.7

from django.db import migrations, models
import django.db.models.deletion


ROUGH_COUNTRY_KIND = 4
PROVIDER_ACTIVE = 1


def backfill_rough_country_company_pricing(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute(
            """
            INSERT INTO rough_country_company_pricing (
                part_id,
                company_id,
                price,
                sale_price,
                cost,
                cnd_map,
                cnd_price,
                created_at,
                updated_at
            )
            SELECT
                p.id,
                cp.company_id,
                p.price,
                p.sale_price,
                p.cost,
                p.cnd_map,
                p.cnd_price,
                NOW(),
                NOW()
            FROM rough_country_parts p
            CROSS JOIN (
                SELECT DISTINCT cp_inner.company_id
                FROM company_providers cp_inner
                INNER JOIN providers pr ON pr.id = cp_inner.provider_id
                WHERE pr.kind = %s AND pr.status = %s
            ) AS cp
            """,
            [ROUGH_COUNTRY_KIND, PROVIDER_ACTIVE],
        )


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0057_keystonecompanypricing"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoughCountryCompanyPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "cnd_map",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "cnd_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rough_country_company_pricing",
                        to="src.company",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_pricing",
                        to="src.roughcountrypart",
                    ),
                ),
            ],
            options={
                "db_table": "rough_country_company_pricing",
                "unique_together": {("part", "company")},
            },
        ),
        migrations.RunPython(
            backfill_rough_country_company_pricing,
            migrations.RunPython.noop,
        ),
    ]
