# Generated by Django 4.1.7

from django.db import migrations, models
import django.db.models.deletion


WHEELPROS_KIND = 5
PROVIDER_ACTIVE = 1


def backfill_wheelpros_company_pricing(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute(
            """
            INSERT INTO wheelpros_company_pricing (
                part_id,
                company_id,
                msrp_usd,
                map_usd,
                created_at,
                updated_at
            )
            SELECT
                p.id,
                cp.company_id,
                p.msrp_usd,
                p.map_usd,
                NOW(),
                NOW()
            FROM wheelpros_parts p
            CROSS JOIN (
                SELECT DISTINCT cp_inner.company_id
                FROM company_providers cp_inner
                INNER JOIN providers pr ON pr.id = cp_inner.provider_id
                WHERE pr.kind = %s AND pr.status = %s
            ) AS cp
            """,
            [WHEELPROS_KIND, PROVIDER_ACTIVE],
        )


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0058_roughcountrycompanypricing"),
    ]

    operations = [
        migrations.CreateModel(
            name="WheelProsCompanyPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "msrp_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "map_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wheelpros_company_pricing",
                        to="src.company",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_pricing",
                        to="src.wheelprospart",
                    ),
                ),
            ],
            options={
                "db_table": "wheelpros_company_pricing",
                "unique_together": {("part", "company")},
            },
        ),
        migrations.RunPython(
            backfill_wheelpros_company_pricing,
            migrations.RunPython.noop,
        ),
    ]
