# Generated by Django 4.1.7

from django.db import migrations, models
import django.db.models.deletion


MEYER_KIND = 6
PROVIDER_ACTIVE = 1


def backfill_meyer_company_pricing(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute(
            """
            INSERT INTO meyer_company_pricing (
                part_id,
                company_id,
                jobber_price,
                cost,
                core_charge,
                map_price,
                created_at,
                updated_at
            )
            SELECT
                mp.id,
                cp.company_id,
                mp.jobber_price,
                mp.cost,
                mp.core_charge,
                mp.map_price,
                NOW(),
                NOW()
            FROM meyer_parts mp
            CROSS JOIN (
                SELECT DISTINCT cp_inner.company_id
                FROM company_providers cp_inner
                INNER JOIN providers pr ON pr.id = cp_inner.provider_id
                WHERE pr.kind = %s AND pr.status = %s
            ) AS cp
            """,
            [MEYER_KIND, PROVIDER_ACTIVE],
        )


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0059_wheelproscompanypricing"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeyerCompanyPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jobber_price",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=14, null=True
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=14, null=True
                    ),
                ),
                (
                    "core_charge",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=14, null=True
                    ),
                ),
                (
                    "map_price",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=14, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meyer_company_pricing",
                        to="src.company",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_pricing",
                        to="src.meyerparts",
                    ),
                ),
            ],
            options={
                "db_table": "meyer_company_pricing",
                "unique_together": {("part", "company")},
            },
        ),
        migrations.RunPython(
            backfill_meyer_company_pricing,
            migrations.RunPython.noop,
        ),
    ]
