# Generated by Django 4.1.7

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0060_meyercompanypricing"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationPricingSyncJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.PositiveSmallIntegerField()),
                ("status_name", models.CharField(max_length=64)),
                ("message", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_sync_jobs",
                        to="src.companyproviders",
                    ),
                ),
            ],
            options={
                "db_table": "integration_pricing_sync_job",
                "ordering": ["id"],
            },
        ),
    ]
