# Generated by Django 4.1.7

from django.db import migrations


def create_atech_provider(apps, schema_editor):
    Providers = apps.get_model("src", "Providers")
    Providers.objects.get_or_create(
        kind=7,
        defaults={
            "name": "A-Tech",
            "status": 1,
            "status_name": "ACTIVE",
            "type": 2,
            "type_name": "DISTRIBUTOR",
            "kind_name": "ATECH",
        },
    )


def remove_atech_provider(apps, schema_editor):
    Providers = apps.get_model("src", "Providers")
    Providers.objects.filter(kind=7).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0061_integrationpricingsyncjob"),
    ]

    operations = [
        migrations.RunPython(create_atech_provider, remove_atech_provider),
    ]
