# Generated by Django 4.1.7

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0062_atech_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtechBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=512)),
                ("name", models.CharField(max_length=512)),
                (
                    "aaia_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "atech_brands",
                "unique_together": {("external_id",)},
            },
        ),
        migrations.CreateModel(
            name="AtechPrefixBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "atech_brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prefix_mappings",
                        to="src.atechbrand",
                    ),
                ),
            ],
            options={
                "db_table": "atech_prefix_brand",
                "unique_together": {("prefix",)},
            },
        ),
        migrations.CreateModel(
            name="AtechParts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_number", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=14, null=True
                    ),
                ),
                (
                    "retail_price",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=14, null=True
                    ),
                ),
                (
                    "jobber_price",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=14, null=True
                    ),
                ),
                ("qty_tallmadge", models.IntegerField(blank=True, null=True)),
                ("qty_sparks", models.IntegerField(blank=True, null=True)),
                ("qty_mcdonough", models.IntegerField(blank=True, null=True)),
                ("qty_arlington", models.IntegerField(blank=True, null=True)),
                (
                    "core_charge",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=14, null=True
                    ),
                ),
                (
                    "fee_hazmat",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=14, null=True
                    ),
                ),
                (
                    "fee_truck_us",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=14, null=True
                    ),
                ),
                (
                    "fee_handling_ground",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=14, null=True
                    ),
                ),
                (
                    "fee_handling_air",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=14, null=True
                    ),
                ),
                ("gtin", models.CharField(blank=True, max_length=64, null=True)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="src.atechbrand",
                    ),
                ),
            ],
            options={
                "db_table": "atech_parts",
                "unique_together": {("part_number", "brand")},
            },
        ),
    ]
