# Generated by Django 4.1.7

from django.db import migrations, models


def backfill_feed_and_stripped_part_numbers(apps, schema_editor):
    AtechParts = apps.get_model("src", "AtechParts")
    for p in AtechParts.objects.all().iterator():
        full = (p.part_number or "").strip()
        if not full:
            continue
        p.feed_part_number = full
        if "-" in full:
            suf = full.split("-", 1)[1].strip()
        else:
            suf = full
        p.part_number = suf
        p.mfr_part_number = suf
        p.save(update_fields=["feed_part_number", "part_number", "mfr_part_number"])


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0063_atech_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="atechparts",
            name="feed_part_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="atechparts",
            name="mfr_part_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="atechparts",
            unique_together=[],
        ),
        migrations.RunPython(backfill_feed_and_stripped_part_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="atechparts",
            name="feed_part_number",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="atechparts",
            unique_together=[("feed_part_number", "brand")],
        ),
    ]
