# Generated by Django 4.1.7

from django.db import migrations, models
import django.db.models.deletion


def backfill_brand_prefix(apps, schema_editor):
    AtechParts = apps.get_model("src", "AtechParts")
    for p in AtechParts.objects.all().iterator():
        full = (p.feed_part_number or "").strip()
        if not full:
            prefix = ""
        elif "-" in full:
            prefix = full.split("-", 1)[0].strip().upper()
        else:
            prefix = full.upper()
        if p.brand_prefix != prefix:
            p.brand_prefix = prefix
            p.save(update_fields=["brand_prefix"])


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0064_atech_parts_feed_and_stripped_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="atechparts",
            name="brand_prefix",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.RunPython(backfill_brand_prefix, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="atechparts",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts",
                to="src.atechbrand",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="atechparts",
            unique_together=[],
        ),
        migrations.AlterUniqueTogether(
            name="atechparts",
            unique_together=[("feed_part_number",)],
        ),
    ]
