# Generated by Django 4.1.7

import django.db.models.deletion
from django.db import migrations, models


def create_dlg_provider(apps, schema_editor):
    Providers = apps.get_model("src", "Providers")
    Providers.objects.get_or_create(
        kind=8,
        defaults={
            "name": "DLG",
            "status": 1,
            "status_name": "ACTIVE",
            "type": 2,
            "type_name": "DISTRIBUTOR",
            "kind_name": "DLG",
        },
    )


def remove_dlg_provider(apps, schema_editor):
    Providers = apps.get_model("src", "Providers")
    Providers.objects.filter(kind=8).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0066_brand_atech_mapping_company_pricing"),
    ]

    operations = [
        migrations.CreateModel(
            name="DlgBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=512)),
                ("name", models.CharField(max_length=512)),
                (
                    "aaia_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dlg_brands",
                "unique_together": {("external_id",)},
            },
        ),
        migrations.CreateModel(
            name="BrandDlgBrandMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dlg_brand_mappings",
                        to="src.brands",
                    ),
                ),
                (
                    "dlg_brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_mappings",
                        to="src.dlgbrand",
                    ),
                ),
            ],
            options={
                "db_table": "brand_dlg_brand_mapping",
                "unique_together": {("brand", "dlg_brand")},
            },
        ),
        migrations.CreateModel(
            name="DlgParts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_number", models.CharField(max_length=255)),
                ("display_name", models.TextField(blank=True, null=True)),
                ("available_on_hand", models.IntegerField(blank=True, null=True)),
                ("units", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "base_price",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=14, null=True
                    ),
                ),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="src.dlgbrand",
                    ),
                ),
            ],
            options={
                "db_table": "dlg_parts",
                "unique_together": {("part_number", "brand")},
            },
        ),
        migrations.RunPython(create_dlg_provider, remove_dlg_provider),
    ]
