# Generated by Django 4.1.7

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0068_dlg_company_pricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="atechparts",
            name="image_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
