# Generated by Django 4.1.7

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0069_atech_parts_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerpart",
            name="distributor_refreshed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last refresh time from the distributor part row (source updated_at) when master parts sync ran.",
                null=True,
            ),
        ),
    ]
