# Generated by Django 4.1.7

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0070_providerpart_distributor_refreshed_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="partrequestaudit",
            index=models.Index(
                fields=["company", "action", "user", "created_at"],
                name="pra_co_act_usr_crt_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partrequestaudit",
            index=models.Index(
                fields=["company", "action", "created_at"],
                name="pra_co_act_crt_idx",
            ),
        ),
    ]
