# Generated by Django 4.1.7

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0071_partrequestaudit_list_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterpart",
            name="overview_category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="masterpart",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="providerpart",
            name="overview_category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="providerpart",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="providerpart",
            name="subcategory",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
