# Generated by Django 4.1.7

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0072_masterpart_overview_category_and_providerpart_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_category", models.CharField(db_index=True, max_length=255)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("overview_category", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "category_mappings",
            },
        ),
    ]
