# Generated by Django 4.1.7

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0073_categorymapping"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="providerpart",
            index=models.Index(fields=["category"], name="pp_category_idx"),
        ),
        migrations.AddIndex(
            model_name="providerpart",
            index=models.Index(fields=["overview_category"], name="pp_overview_category_idx"),
        ),
    ]
