# Generated by Django 4.1.7

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0074_providerpart_category_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="wheelprospart",
            name="feed_type",
            field=models.CharField(
                blank=True,
                help_text="Which SFTP feed last wrote this row: wheel, tire, or accessories.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wheelproscompanypricing",
            name="cost_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Dealer cost derived from MSRP and company wheel/tire/accessories discount % in credentials.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
