# Generated by Django 4.1.7 on 2026-06-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0081_lead_ai_skip_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="uszipcode",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
