# Generated by Django 4.1.7 on 2026-06-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0082_alter_lead_id_alter_uszipcode_id'),
        ('src', '0082_lead_email_verification'),
    ]

    operations = [
    ]
