# Generated by Django 4.1.7 on 2026-06-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0083_merge_20260602_1325'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leademail',
            name='lead_email_unique',
        ),
        migrations.AddField(
            model_name='lead',
            name='website_not_found',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='leademail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='leademail',
            unique_together={('lead', 'email')},
        ),
    ]
