# Generated by Django 4.1.7 on 2026-06-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0084_add_website_not_found_to_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='emails_not_found',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
