# Generated by Django 4.1.7 on 2026-06-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0085_add_emails_not_found_to_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='leademail',
            name='ai_valid',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
