# Generated by Django 4.1.7 on 2026-07-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0094_custom_integration_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="relay_sftp_password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="relay_sftp_provisioned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="relay_sftp_username",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
