# Generated by Django 4.1.7 on 2026-07-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0095_company_relay_sftp_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyproviders",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
