# Generated by Django 4.1.7 on 2026-07-16 09:37

from django.db import migrations, models
import django.db.models.deletion


def create_asap_network_provider(apps, schema_editor):
    Providers = apps.get_model("src", "Providers")
    # update_or_create (not get_or_create): a stray Providers row for kind=34 already existed in
    # at least one environment with type=DISTRIBUTOR — force it to CATALOG here rather than
    # silently leaving a pre-existing wrong value in place.
    Providers.objects.update_or_create(
        kind=34,  # BrandProviderKind.ASAP_NETWORK
        defaults={
            "name": "ASAP Network",
            "status": 1,
            "status_name": "ACTIVE",
            "type": 1,
            "type_name": "CATALOG",
            "kind_name": "ASAP_NETWORK",
        },
    )


def remove_asap_network_provider(apps, schema_editor):
    Providers = apps.get_model("src", "Providers")
    Providers.objects.filter(kind=34).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0108_purchase_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsapBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('term_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Set once a full product sync for this brand completes; skipped on future runs unless --force (ASAP is a paid API).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'asap_brands',
            },
        ),
        migrations.CreateModel(
            name='MasterPartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('series', models.CharField(blank=True, max_length=255, null=True)),
                ('warranty', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_type', models.JSONField(blank=True, null=True)),
                ('field_specs', models.JSONField(blank=True, null=True)),
                ('youtube_video', models.CharField(blank=True, max_length=500, null=True)),
                ('installation_instructions', models.JSONField(blank=True, null=True)),
                ('source_external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'master_part_data',
            },
        ),
        migrations.CreateModel(
            name='MasterPartFitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('make', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('submodel', models.CharField(blank=True, default='', max_length=255)),
                ('engine', models.CharField(blank=True, default='', max_length=255)),
                ('drive_type', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'master_part_fitments',
            },
        ),
        migrations.AddField(
            model_name='masterpartfitment',
            name='master_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='src.masterpart'),
        ),
        migrations.AddField(
            model_name='masterpartfitment',
            name='source_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fitments', to='src.providers'),
        ),
        migrations.AddField(
            model_name='masterpartdata',
            name='master_part',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='src.masterpart'),
        ),
        migrations.AddField(
            model_name='masterpartdata',
            name='source_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_part_data', to='src.providers'),
        ),
        migrations.AddField(
            model_name='asapbrand',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asap_brands', to='src.brands'),
        ),
        migrations.AlterUniqueTogether(
            name='masterpartfitment',
            unique_together={('master_part', 'year_start', 'year_end', 'make', 'model', 'submodel', 'engine', 'drive_type')},
        ),
        migrations.RunPython(create_asap_network_provider, remove_asap_network_provider),
    ]
