# Generated by Django 4.1.7 on 2026-08-08 21:49

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0152_motorstate_availability_global"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandWpsBrandMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "brand_wps_brand_mapping",
            },
        ),
        migrations.CreateModel(
            name="WpsBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wps_brands",
            },
        ),
        migrations.CreateModel(
            name="WpsCompanyPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "list_price",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "dealer_price",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "map_price",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("has_map_policy", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wps_company_pricing",
            },
        ),
        migrations.CreateModel(
            name="WpsInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=32, null=True)),
                ("sku", models.CharField(max_length=128, null=True)),
                ("ca_warehouse", models.IntegerField(default=0)),
                ("ga_warehouse", models.IntegerField(default=0)),
                ("id_warehouse", models.IntegerField(default=0)),
                ("in_warehouse", models.IntegerField(default=0)),
                ("pa_warehouse", models.IntegerField(default=0)),
                ("pa2_warehouse", models.IntegerField(default=0)),
                ("tx_warehouse", models.IntegerField(default=0)),
                ("total", models.IntegerField(default=0)),
                ("source_updated_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wps_inventory",
            },
        ),
        migrations.CreateModel(
            name="WpsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=32)),
                ("sku", models.CharField(max_length=128, null=True)),
                ("name", models.CharField(max_length=255, null=True)),
                ("supplier_product_id", models.CharField(max_length=128, null=True)),
                ("upc", models.CharField(max_length=64, null=True)),
                ("superseded_sku", models.CharField(max_length=128, null=True)),
                ("status", models.CharField(max_length=16, null=True)),
                ("product_type", models.CharField(max_length=255, null=True)),
                ("length", models.FloatField(null=True)),
                ("width", models.FloatField(null=True)),
                ("height", models.FloatField(null=True)),
                ("weight", models.FloatField(null=True)),
                ("has_map_policy", models.BooleanField(default=False)),
                ("drop_ship_eligible", models.BooleanField(default=False)),
                ("drop_ship_fee", models.CharField(max_length=32, null=True)),
                ("source_updated_at", models.DateTimeField(null=True)),
                ("data", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wps_items",
            },
        ),
        migrations.AddField(
            model_name="wpsitem",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="src.wpsbrand",
            ),
        ),
        migrations.AddField(
            model_name="wpsinventory",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to="src.wpsitem",
            ),
        ),
        migrations.AddField(
            model_name="wpscompanypricing",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wps_company_pricing",
                to="src.company",
            ),
        ),
        migrations.AddField(
            model_name="wpscompanypricing",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_pricing",
                to="src.wpsitem",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wpsbrand",
            unique_together={("external_id",)},
        ),
        migrations.AddField(
            model_name="brandwpsbrandmapping",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wps_brand_mappings",
                to="src.brands",
            ),
        ),
        migrations.AddField(
            model_name="brandwpsbrandmapping",
            name="wps_brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand_mappings",
                to="src.wpsbrand",
            ),
        ),
        migrations.AddIndex(
            model_name="wpsitem",
            index=models.Index(fields=["brand"], name="wps_items_brand_idx"),
        ),
        migrations.AddIndex(
            model_name="wpsitem",
            index=models.Index(
                fields=["source_updated_at"], name="wps_items_updated_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wpsitem",
            index=models.Index(fields=["sku"], name="wps_items_sku_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="wpsitem",
            unique_together={("external_id",)},
        ),
        migrations.AlterUniqueTogether(
            name="wpscompanypricing",
            unique_together={("item", "company")},
        ),
        migrations.AlterUniqueTogether(
            name="brandwpsbrandmapping",
            unique_together={("brand", "wps_brand")},
        ),
    ]
