# Generated by Django 4.1.7 on 2026-08-08 22:01

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0153_wps_raw_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="WpsProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(null=True)),
                ("data", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wps_products",
            },
        ),
        migrations.CreateModel(
            name="WpsWarehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=32)),
                ("db2_key", models.CharField(max_length=16, null=True)),
                ("name", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wps_warehouses",
            },
        ),
        migrations.AddField(
            model_name="wpsitem",
            name="image_url",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="wpsitem",
            name="images",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="wpsitem",
            name="taxonomy",
            field=models.JSONField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name="wpswarehouse",
            unique_together={("external_id",)},
        ),
        migrations.AlterUniqueTogether(
            name="wpsproduct",
            unique_together={("external_id",)},
        ),
        migrations.AddField(
            model_name="wpsitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="src.wpsproduct",
            ),
        ),
    ]
