# Generated by Django 4.1.7 on 2026-08-20 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0171_merge_realtruck_and_product_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductLineTerminologyMap",
            fields=[
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="terminology_map",
                        serialize=False,
                        to="src.productgroup",
                    ),
                ),
                ("part_terminology_id", models.IntegerField(blank=True, null=True)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("source", models.CharField(max_length=32)),
                ("splits", models.JSONField(blank=True, null=True)),
                ("reasoning", models.TextField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "product_line_terminology_map",
            },
        ),
        migrations.AddField(
            model_name="masterpart",
            name="part_terminology_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
