# Generated by Django 4.1.7 on 2026-08-21 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0172_stage_i_terminology_map"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLPartTerminologyClassification",
            fields=[
                (
                    "master_part",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ml_terminology_classification",
                        serialize=False,
                        to="src.masterpart",
                    ),
                ),
                ("status", models.CharField(default="classified", max_length=16)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "subcategory",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stage1_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("part_terminology_id", models.IntegerField(blank=True, null=True)),
                (
                    "stage2_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("reasoning", models.TextField(blank=True, null=True)),
                ("model_used", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ml_part_terminology_classification",
            },
        ),
    ]
