# Generated by Django 4.1.7 on 2026-08-27 13:42

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0185_simpletire_skus'),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelProsVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField(blank=True, db_index=True, help_text="Wheel Pros' own vehicle id ('id'). Indexed, but NOT unique -- see the class docstring.", null=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('make', models.CharField(db_index=True, max_length=128)),
                ('model', models.CharField(db_index=True, max_length=255)),
                ('submodel', models.CharField(blank=True, default='', help_text='"" is the model-level record; anything else is a specific submodel.', max_length=255)),
                ('staggered', models.BooleanField(blank=True, help_text='properties.staggered -- front and rear take different wheel sizes. NULL if unpublished.', null=True)),
                ('vehicle_types', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Which ?type= listings this vehicle appeared under, e.g. ["wheel", "tire"]. The detail payload does not say, so this is recorded from the listing calls that found it.')),
                ('raw_payload', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='The detail response verbatim, axles included. Re-parse from here; never re-crawl.', null=True)),
                ('scraped_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this row was last fetched.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wheelpros_vehicles',
            },
        ),
        migrations.CreateModel(
            name='WheelProsVehicleAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('front', 'Front'), ('rear', 'Rear')], max_length=8)),
                ('code', models.CharField(blank=True, help_text="Wheel Pros' axle code.", max_length=64, null=True)),
                ('bolt_pattern_mm', models.CharField(blank=True, db_index=True, help_text='Lug count x circle diameter as published, e.g. "5x114.3". Text: not a single number.', max_length=64, null=True)),
                ('center_bore_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('hub_code', models.CharField(blank=True, max_length=64, null=True)),
                ('hub_clearance_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('nut_bolt', models.CharField(blank=True, help_text='Whether the wheel is retained by nuts or bolts.', max_length=64, null=True)),
                ('oe_hex', models.CharField(blank=True, help_text='oeHexTx -- OE lug hex size.', max_length=64, null=True)),
                ('lug_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lug_nut_size', models.CharField(blank=True, help_text='lugNutSizeTx, e.g. "M14x1.5".', max_length=64, null=True)),
                ('lug_style_am', models.CharField(blank=True, help_text='amLugStyle -- the aftermarket lug style that fits.', max_length=64, null=True)),
                ('oe_width_in', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_width_in', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('oe_diameter_in', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('min_diameter_in', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_diameter_in', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_bs', models.DecimalField(blank=True, decimal_places=2, help_text='Max backspacing, inches.', max_digits=6, null=True)),
                ('max_fs', models.DecimalField(blank=True, decimal_places=2, help_text='Max frontspacing, inches.', max_digits=6, null=True)),
                ('oe_offset_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('offset_min_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('offset_max_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('lift_offset_min_mm', models.DecimalField(blank=True, decimal_places=2, help_text='Offset envelope once the vehicle is lifted -- wider than the stock one.', max_digits=7, null=True)),
                ('lift_offset_max_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('caliper_peak_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('caliper_depth_90mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('caliper_depth_100mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('caliper_depth_106mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('caliper_depth_119mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('caliper_depth_134mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('caliper_depth_160mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('oe_tire', models.CharField(blank=True, help_text='oeTireTx, e.g. "275/55R20". A size expression, not a number.', max_length=64, null=True)),
                ('min_wheel_load', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum wheel load rating, as published.', max_digits=10, null=True)),
                ('pressure_sensor', models.CharField(blank=True, help_text='vehiclePressureSensor -- TPMS type.', max_length=128, null=True)),
                ('sensor_part_number_oe', models.CharField(blank=True, max_length=128, null=True)),
                ('y_factor', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('y_factor_25', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('y_factor_50', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('raw_axle', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='This axle object verbatim.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wheelpros_vehicle_axles',
            },
        ),
        migrations.AddField(
            model_name='wheelprosvehicleaxle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axles', to='src.wheelprosvehicle'),
        ),
        migrations.AddIndex(
            model_name='wheelprosvehicle',
            index=models.Index(fields=['year', 'make', 'model'], name='wheelpros_veh_ymm_idx'),
        ),
        migrations.AddIndex(
            model_name='wheelprosvehicle',
            index=models.Index(fields=['make', 'model'], name='wheelpros_veh_mm_idx'),
        ),
        migrations.AddConstraint(
            model_name='wheelprosvehicle',
            constraint=models.UniqueConstraint(fields=('year', 'make', 'model', 'submodel'), name='wheelpros_vehicle_ymms_uniq'),
        ),
        migrations.AddIndex(
            model_name='wheelprosvehicleaxle',
            index=models.Index(fields=['bolt_pattern_mm', 'position'], name='wheelpros_axle_bolt_pos_idx'),
        ),
        migrations.AddConstraint(
            model_name='wheelprosvehicleaxle',
            constraint=models.UniqueConstraint(fields=('vehicle', 'position'), name='wheelpros_vehicle_axle_uniq'),
        ),
    ]
