"""
Landing table for the TDG Access catalog pull -- see ``src/integrations/services/tdg.py`` and the
``fetch_tdg_catalog`` command.

One row per TDG SKU of *every* product type (tire, wheel, lug kit, hub ring, generic, service),
keyed on their ``id``. Additive only: one new table, three indexes, nothing else touched.
(``makemigrations`` also wanted ~30 unrelated AlterField/RemoveConstraint/AlterUniqueTogether
operations for pre-existing drift between models.py and the migration history -- the same drift
0185 and 0186 stepped around. They are somebody else's change and were removed here so this
migration stays reviewable and independently revertible.)
"""
# Generated by Django 4.1.7 on 2026-08-29 07:33

import django.core.serializers.json
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0188_tire_spec_simpletire_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='TdgProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdg_id', models.BigIntegerField(help_text="TDG's SKU id ('id'). Natural key and upsert target.", unique=True)),
                ('item_number', models.CharField(db_index=True, help_text="TDG's own SKU code, e.g. 'AT-AH4126'. Unique in practice; what their other endpoints take.", max_length=64)),
                ('part_number', models.CharField(blank=True, db_index=True, help_text="Manufacturer part number, e.g. 'AH4126'. Not unique -- two brands can collide.", max_length=64, null=True)),
                ('gtin', models.CharField(blank=True, db_index=True, help_text='Usually the UPC. Absent on ~1/3 of the catalog; leading zeros are significant, so stored as sent.', max_length=32, null=True)),
                ('product_type', models.CharField(choices=[('Tire', 'Tire'), ('Wheel', 'Wheel'), ('Lug Kit', 'Lug kit'), ('Hub Ring', 'Hub ring'), ('Generic Product', 'Generic product'), ('Service', 'Service')], db_index=True, help_text="TDG's 'type', verbatim. Decides which block of spec columns below is populated.", max_length=32)),
                ('brand_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('brand_name', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('product_line_id', models.IntegerField(blank=True, db_index=True, help_text="TDG's 'productId' -- the MODEL, shared by every size. Not the SKU id; see tdg_id.", null=True)),
                ('product_line_name', models.CharField(blank=True, help_text="TDG's 'productName', e.g. 'Grip 20'.", max_length=255, null=True)),
                ('is_inactive', models.BooleanField(db_index=True, default=False, help_text='Discontinued/delisted at TDG. ~20% of tires and over half of wheels. Still returned by the API.')),
                ('is_availability_restricted', models.BooleanField(default=False)),
                ('product_image_url', models.TextField(blank=True, help_text="RideStyler render, ~800px transparent PNG. Per PRODUCT LINE, not per SKU -- every size of a model repeats one URL, and a URL shared by several lines is a placeholder, not that model's photo. Check for reuse before trusting one as a product image.", null=True)),
                ('tire_size_raw', models.CharField(blank=True, help_text="'size' verbatim: '2255517, P225/55R17 XL'.", max_length=64, null=True)),
                ('tire_size_code', models.CharField(blank=True, help_text="Digits-only half of 'size': '2255517'.", max_length=32, null=True)),
                ('tire_size_display', models.CharField(blank=True, db_index=True, help_text="Printed half of 'size': 'P225/55R17 XL'. Feed this to src.domain.tire_size, not the raw field.", max_length=64, null=True)),
                ('tire_size_type', models.CharField(blank=True, help_text='Metric / Flotation / Commerial [sic, their spelling] / Slick.', max_length=16, null=True)),
                ('tire_type', models.CharField(blank=True, help_text="Coded category: 'AS - All Season Tire', '4 - Commercial Truck Tires'. Contains HTML entities.", max_length=64, null=True)),
                ('season', models.CharField(blank=True, db_index=True, help_text='All Season / Winter / Summer / All Weather.', max_length=32, null=True)),
                ('service_type', models.CharField(blank=True, help_text="'P-Passenger', 'LT'.", max_length=32, null=True)),
                ('service_description', models.CharField(blank=True, help_text="Load index + speed symbol as printed: '101T'.", max_length=16, null=True)),
                ('load_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('speed_rating', models.CharField(blank=True, max_length=8, null=True)),
                ('load_range', models.CharField(blank=True, help_text='SL / XL / C / D / E ...', max_length=8, null=True)),
                ('rim_diameter_in', models.DecimalField(blank=True, decimal_places=2, help_text="Their 'wheelDiameter' -- the tire's rim size.", max_digits=5, null=True)),
                ('outside_diameter_in', models.DecimalField(blank=True, decimal_places=2, help_text='UNRELIABLE -- often the section width, not the diameter. See the class docstring.', max_digits=6, null=True)),
                ('tread_depth_32nds', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sidewall', models.CharField(blank=True, help_text="'Black Sidewall', 'Outlined White Letters'.", max_length=32, null=True)),
                ('rim_width_min_in', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rim_width_max_in', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('utqg', models.CharField(blank=True, help_text="Verbatim, space-separated: '400 A A'.", max_length=16, null=True)),
                ('utqg_treadwear', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('utqg_traction', models.CharField(blank=True, max_length=4, null=True)),
                ('utqg_temperature', models.CharField(blank=True, max_length=4, null=True)),
                ('warranty_mileage_miles', models.PositiveIntegerField(blank=True, null=True)),
                ('is_run_flat', models.BooleanField(blank=True, null=True)),
                ('is_ev_optimized', models.BooleanField(blank=True, help_text="Their 'eVOptimized'. Sent on every tire, so rarely NULL.", null=True)),
                ('is_3pmsf', models.BooleanField(blank=True, help_text="Parsed from 'otherAttributeS', whose only observed value is '3PMS'. Absent means TDG made no claim -- NULL, not False. This is a certification with legal weight in some jurisdictions; do not coerce.", null=True)),
                ('winter_studding', models.CharField(blank=True, help_text="'Studdable' or 'Studded' -- factory-studded is not the same.", max_length=16, null=True)),
                ('stud_size', models.CharField(blank=True, help_text="'#12', '#12/13'.", max_length=16, null=True)),
                ('oe_marking', models.CharField(blank=True, db_index=True, help_text="OE homologation as printed: 'MO - Mercedes-Benz', '* - BMW'. May list several, comma-separated.", max_length=64, null=True)),
                ('additional_model_information', models.CharField(blank=True, max_length=128, null=True)),
                ('wheel_diameter_in', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wheel_width_in', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bolt_pattern', models.CharField(blank=True, db_index=True, help_text="As printed: '5x114.3'. Dual-drilled wheels carry both, comma-separated ('6x135, 6x139.7') -- ~6% of them -- so match by containment, not equality.", max_length=32, null=True)),
                ('offset_mm', models.SmallIntegerField(blank=True, help_text='Can be negative.', null=True)),
                ('centerbore_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_load_lb', models.PositiveIntegerField(blank=True, null=True)),
                ('wheel_type', models.CharField(blank=True, help_text="Their wheel-only 'type' key: Alloy / Steel / Specialty.", max_length=32, null=True)),
                ('construction', models.CharField(blank=True, help_text='Cast / Forged / Stamp & Weld / Alloy ...', max_length=32, null=True)),
                ('lug_seat', models.CharField(blank=True, help_text='Conical / Spherical / Flat.', max_length=16, null=True)),
                ('is_winter_approved', models.BooleanField(blank=True, null=True)),
                ('thread', models.CharField(blank=True, help_text='\'14mm x 1.50\', \'9/16" x 18\'.', max_length=32, null=True)),
                ('seat', models.CharField(blank=True, help_text='Conical / Radius / Shank.', max_length=16, null=True)),
                ('style', models.CharField(blank=True, help_text='Acorn / Spline / Tuner.', max_length=16, null=True)),
                ('end_type', models.CharField(blank=True, help_text='Closed / Open / Closed End.', max_length=16, null=True)),
                ('inside_diameter_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('overall_diameter_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('finish', models.CharField(blank=True, max_length=64, null=True)),
                ('material', models.CharField(blank=True, help_text="Aluminum / Steel / Alloy / Plastic / 'Unspecified'.", max_length=32, null=True)),
                ('superseded_by_item', models.CharField(blank=True, help_text="TDG's replacement for a discontinued SKU. Their id, not ours -- resolve before use.", max_length=32, null=True)),
                ('raw', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='The product object verbatim, specifications included. Backfill new columns from here, not a re-pull.', null=True)),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tdg_products',
            },
        ),
        migrations.AddIndex(
            model_name='tdgproduct',
            index=models.Index(fields=['product_type', 'brand_name'], name='tdg_type_brand_idx'),
        ),
        migrations.AddIndex(
            model_name='tdgproduct',
            index=models.Index(fields=['brand_name', 'part_number'], name='tdg_brand_part_idx'),
        ),
        migrations.AddIndex(
            model_name='tdgproduct',
            index=models.Index(fields=['product_line_id'], name='tdg_product_line_idx'),
        ),
    ]
