"""
Create the brand-data department's three tables: ``tire_brand_sources``, ``tire_brand_source_runs``
and ``raw_tire_specs``.

Where a manufacturer's own tire data comes from, every attempt to pull it, and what those pulls
landed. See ``src/integrations/brand_data/`` for the machinery and
``docs/BRAND_TIRE_DATA_INITIATIVE.md`` for the plan. Additive only: three new tables, their
indexes, and nothing else touched -- in particular nothing in ``tire_specs``, which this phase
deliberately does not write to.

Hand-trimmed rather than left as makemigrations emitted it. Autodetect wanted ~30 unrelated
operations for pre-existing drift between models.py and the migration history -- BigAutoField id
changes across the Premier/Vossen/TireRack tables, CustomIntegrationRequest and PremierBrand
constraint churn -- the same drift 0185, 0186, 0189 and 0196 stepped around. They are somebody
else's change; removing them keeps this migration reviewable and independently revertible.
"""
# Generated by Django 4.1.7 on 2026-08-31 12:06

import django.contrib.postgres.fields
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0197_wheel_specs'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawTireSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_key', models.CharField(help_text="The brand's own SKU/article number, or a digest of brand+part+size when they publish none.", max_length=255)),
                ('part_number', models.CharField(blank=True, max_length=128, null=True)),
                ('part_number_key', models.CharField(blank=True, db_index=True, help_text='part_number through tire_catalog.part_key -- punctuation stripped. What a match joins on.', max_length=128, null=True)),
                ('gtin', models.CharField(blank=True, db_index=True, help_text='UPC/EAN as printed. Leading zeros are significant, so text, not a number.', max_length=32, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=128, null=True)),
                ('brand_key', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('model_key', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_model', models.CharField(blank=True, help_text="A line's variant where the brand names one separately: 'Plus', 'ZP', 'OE'.", max_length=255, null=True)),
                ('size_raw', models.CharField(blank=True, help_text='The size cell verbatim, whatever else it had glued to it.', max_length=128, null=True)),
                ('size_display', models.CharField(blank=True, db_index=True, help_text='The size alone, cleaned of surrounding text but NOT normalized. Fed to src.domain.tire_size.', max_length=64, null=True)),
                ('service_type', models.CharField(blank=True, help_text='P / LT / ST / T.', max_length=16, null=True)),
                ('load_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('load_index_dual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('speed_rating', models.CharField(blank=True, max_length=8, null=True)),
                ('load_range', models.CharField(blank=True, max_length=8, null=True)),
                ('ply_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parsed_size', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='OUR decode of size_display via src.domain.tire_size, kept apart from the published columns so the two can never be confused. NULL = the string did not parse; that query is how a broken size column is found.', null=True)),
                ('tread_depth_32nds', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_load_lb', models.PositiveIntegerField(blank=True, null=True)),
                ('max_load_dual_lb', models.PositiveIntegerField(blank=True, null=True)),
                ('max_psi', models.PositiveSmallIntegerField(blank=True, help_text='As published. NEVER derived from load range.', null=True)),
                ('rim_width_min_in', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rim_width_max_in', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('measured_rim_width_in', models.DecimalField(blank=True, decimal_places=2, help_text='The rim the published dimensions were measured on -- a single width inside the approved range, not the range. Only a manufacturer publishes this, and without it their diameter and section width are figures with no stated conditions.', max_digits=5, null=True)),
                ('overall_diameter_in', models.DecimalField(blank=True, decimal_places=2, help_text="MEASURED, on measured_rim_width_in. Not the same quantity as tire_specs.overall_diameter_in, which is the diameter the size prints and what '35 inch' search matches. Do not copy one into the other.", max_digits=6, null=True)),
                ('section_width_in', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tire_weight_lb', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('revs_per_mile', models.PositiveIntegerField(blank=True, help_text='Revolutions per mile. Published by manufacturers, by essentially no reseller, and the honest input to a speedometer-error calculation.', null=True)),
                ('utqg', models.CharField(blank=True, help_text="Verbatim, e.g. '500 A A'.", max_length=16, null=True)),
                ('utqg_treadwear', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('utqg_traction', models.CharField(blank=True, max_length=4, null=True)),
                ('utqg_temperature', models.CharField(blank=True, max_length=4, null=True)),
                ('sidewall_style', models.CharField(blank=True, help_text='Blackwall / Outlined White Letters / Raised White Letters.', max_length=64, null=True)),
                ('tread_design', models.CharField(blank=True, help_text='Symmetrical / Asymmetrical / Directional.', max_length=32, null=True)),
                ('mileage_warranty_miles', models.PositiveIntegerField(blank=True, null=True)),
                ('commercial_position', models.CharField(blank=True, help_text='Steer / Drive / Trailer / All Position.', max_length=32, null=True)),
                ('oe_marking', models.CharField(blank=True, db_index=True, help_text="Homologation codes as printed ('MO', 'N0', '*'). The manufacturer is the only party who actually knows this, which is a large part of why this table exists.", max_length=128, null=True)),
                ('season_label', models.CharField(blank=True, help_text="The brand's own season word, untranslated.", max_length=64, null=True)),
                ('category_label', models.CharField(blank=True, help_text="The brand's own tread/segment word ('Highway All-Season', 'Ultra High Performance'), untranslated. Mapping it to our TreadCategory is a later, reviewable step.", max_length=64, null=True)),
                ('vehicle_class_label', models.CharField(blank=True, max_length=64, null=True)),
                ('is_3pmsf', models.BooleanField(blank=True, help_text="Three-Peak Mountain Snowflake. A certification with legal weight; absence is unknown, not 'no'.", null=True)),
                ('is_ms', models.BooleanField(blank=True, null=True)),
                ('is_run_flat', models.BooleanField(blank=True, null=True)),
                ('is_studdable', models.BooleanField(blank=True, null=True)),
                ('is_tubeless', models.BooleanField(blank=True, null=True)),
                ('has_reinforced_sidewall', models.BooleanField(blank=True, null=True)),
                ('is_discontinued', models.BooleanField(blank=True, help_text="The brand's own word on it, where they say. Not inferred from absence.", null=True)),
                ('product_url', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('spec_sheet_url', models.TextField(blank=True, help_text='The PDF/page this row was read off, where there is one to point at.', null=True)),
                ('raw', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='The source record verbatim. Re-map from here; never re-pull to fix a mapping.', null=True)),
                ('attributes', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Every published label -> value, flattened -- including everything no column covers. Query this before adding a column.')),
                ('warnings', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text="What did not parse on this row, e.g. 'size did not parse', 'tread_depth: 11/32nds ea.'. The triage list.", size=None)),
                ('content_hash', models.CharField(help_text='sha256 of the mapped values plus raw. Unchanged means the run has nothing to write for this row.', max_length=64)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_changed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When a value last actually moved -- not when we last looked.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'raw_tire_specs',
            },
        ),
        migrations.CreateModel(
            name='TireBrandSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Stable id, e.g. 'michelin' or 'michelin-databook'. Natural key; seeds upsert on it.", max_length=128, unique=True)),
                ('brand_name', models.CharField(db_index=True, help_text='The manufacturer, spelled as they spell it. Free text on purpose -- a source can exist for a brand we do not carry yet.', max_length=128)),
                ('method', models.CharField(choices=[('csv', 'File drop (CSV / spreadsheet)'), ('manual', 'Manual entry'), ('api', 'API pull'), ('scrape', 'Scrape')], db_index=True, help_text='How the data reaches us. Decides whether the source can run unattended, not which code runs.', max_length=16)),
                ('handler', models.CharField(blank=True, default='', help_text="Loader key registered in src.integrations.brand_data.registry, e.g. 'csv' or 'http_json'. Blank means the pull is not built yet -- valid, and the point of a 'planned' row.", max_length=64)),
                ('status', models.CharField(choices=[('planned', 'Planned -- no loader or no data yet'), ('active', 'Active'), ('paused', 'Paused -- do not schedule'), ('retired', 'Retired -- kept for the rows it left behind')], db_index=True, default='planned', max_length=16)),
                ('config', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text="Everything the loader needs and nothing secret: path/url, column or JSON-path map under 'field_map', pagination, row filters. Shape is per handler and validated when the source runs.")),
                ('credential_setting', models.CharField(blank=True, default='', help_text='NAME of the Django setting / env var holding the key. Never the key itself.', max_length=64)),
                ('source_url', models.TextField(blank=True, default='', help_text='Where the data comes from, for a human: the dealer portal, the data-book page, the API docs.')),
                ('notes', models.TextField(blank=True, default='', help_text="What a person has to do to refresh this, in enough detail that somebody else can do it. The only documentation a 'manual' source has.")),
                ('contact', models.CharField(blank=True, default='', help_text='Rep or mailbox the file comes from, where there is one.', max_length=255)),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text="Lower runs first, and wins where two sources describe the same tire -- a brand's own API outranks a scrape of their marketing site. Only meaningful between sources; manufacturer data as a whole outranks the reseller catalogs by being in this table.")),
                ('refresh_interval_days', models.PositiveSmallIntegerField(blank=True, help_text='How often this is worth re-pulling. NULL = on demand only; nothing schedules it.', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_row_count', models.PositiveIntegerField(blank=True, help_text='Rows the last successful run saw. A sudden drop is the cheapest signal that a source broke.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tire_brand_sources',
            },
        ),
        migrations.CreateModel(
            name='TireBrandSourceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped -- input unchanged')], db_index=True, default='running', max_length=16)),
                ('dry_run', models.BooleanField(default=False, help_text='Read and map, write no spec rows.')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('input_label', models.TextField(blank=True, default='', help_text='What was read: the file path, or the URL and page count.')),
                ('input_fingerprint', models.CharField(blank=True, default='', help_text='sha256 of the bytes read. Same as last run = the source has not changed.', max_length=64)),
                ('rows_seen', models.PositiveIntegerField(default=0, help_text='Records the loader produced.')),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('rows_unchanged', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0, help_text='Records dropped before writing: filtered out, or carrying nothing that identifies a tire.')),
                ('rows_with_warnings', models.PositiveIntegerField(default=0, help_text='Written, but something did not parse -- see RawTireSpec.warnings.')),
                ('error', models.TextField(blank=True, default='')),
                ('stats', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Per-run detail worth keeping but not worth a column: warning histogram, unmapped source columns.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tire_brand_source_runs',
            },
        ),
        migrations.AddField(
            model_name='tirebrandsourcerun',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='src.tirebrandsource'),
        ),
        migrations.AddField(
            model_name='tirebrandsource',
            name='brand',
            field=models.ForeignKey(blank=True, help_text="Our catalog's brand row, once somebody has confirmed the two are the same manufacturer. NULL until then, and deliberately not required: matching rows into master_parts is a later step and must not be a precondition for collecting them.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tire_data_sources', to='src.brands'),
        ),
        migrations.AddField(
            model_name='rawtirespec',
            name='last_seen_run',
            field=models.ForeignKey(blank=True, help_text="Last run that found this row present. Rows the newest run did not see are the source's deletions.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rows_seen_here', to='src.tirebrandsourcerun'),
        ),
        migrations.AddField(
            model_name='rawtirespec',
            name='source',
            field=models.ForeignKey(help_text="CASCADE: these rows are that source's output and mean nothing without it.", on_delete=django.db.models.deletion.CASCADE, related_name='raw_tire_specs', to='src.tirebrandsource'),
        ),
        migrations.AddIndex(
            model_name='tirebrandsourcerun',
            index=models.Index(fields=['source', '-started_at'], name='tire_brand_run_source_idx'),
        ),
        migrations.AddIndex(
            model_name='tirebrandsource',
            index=models.Index(fields=['status', 'method'], name='tire_brand_src_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tirebrandsource',
            index=models.Index(fields=['priority', 'brand_name'], name='tire_brand_src_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtirespec',
            index=models.Index(fields=['brand_key', 'part_number_key'], name='raw_tire_brand_part_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtirespec',
            index=models.Index(fields=['brand_key', 'size_display'], name='raw_tire_brand_size_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtirespec',
            index=models.Index(fields=['source', '-last_seen_at'], name='raw_tire_source_seen_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rawtirespec',
            unique_together={('source', 'external_key')},
        ),
    ]
