"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-yn^dlc9j100z&q5x!sx5m4*9z6g-k*zcibu_p3#f(fv=b&yr^z"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["5.161.121.143"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "src",
]

MIGRATION_MODULES = {
    "src": "migrations",
}
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.common.CommonMiddleware",
    #"django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "src.authentication.middleware.JWTAuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:8080',
    'http://localhost:80',
    'http://142.132.187.151:8005',
    'http://142.132.187.151:8007',
    'http://142.132.187.151:8000',
    'http://142.132.187.151:8080',
    'http://142.132.187.151:80',
    'https://142.132.187.151:443',
    'http://49.13.0.20:8005',
    'http://49.13.0.20:8007',
    'http://49.13.0.20:8000',
    'https://shopifyanalytics.netlify.app',
    'http://frontend:8000',
    'http://frontend:8080',
    'http://frontend:80',
    'https://dashboard.crotechflow.com',
    'https://www.dashboard.crotechflow.com',
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = "urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wsgi.application"

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTHENTICATION_BACKENDS = [
    "src.authentication.backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
    },
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(name)s.%(funcName)s:%(lineno)s %(message)s"
        },
    },
}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "<TAG>",
        "USER": "<TAG>",
        "PASSWORD": "<TAG>",
        "HOST": "<TAG>",
        "PORT": "<TAG>",
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "<TAG>",
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
    }
}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "mail.jsoncargo.com"
EMAIL_PORT = 587
EMAIL_USE_SSL = False
EMAIL_HOST_USER = "noreply@jsoncargo.com"
EMAIL_HOST_PASSWORD = "your-email-account-password"  # Replace with the actual password
DEFAULT_FROM_EMAIL = "noreply@jsoncargo.com"

LOGGING_EMAIL_RECIPIENT_LIST = ["hajdukbet@gmail.com"]

TURN14_BASE_URL = 'https://api.turn14.com/v1'

# Keystone FTP (implicit FTPS, port 990)
KEYSTONE_FTP_HOST = 'ftp.ekeystone.com'
KEYSTONE_FTP_PORT = 990
KEYSTONE_FTP_USER = ''  # Set via env or CompanyProviders.credentials
KEYSTONE_FTP_PASSWORD = ''
KEYSTONE_INVENTORY_LOCAL_PATH = '/tmp/keystone_inventory.csv'

# Rough Country jobber feed (Excel). Override ROUGH_COUNTRY_FEED_URL if the default returns 403.
ROUGH_COUNTRY_FEED_URL = "https://feeds.roughcountry.com/jobber_pc2A.xlsx"

# Stripe (billing portal + checkout)
STRIPE_SECRET_KEY = ""  # Set via env; required for billing
BILLING_PORTAL_RETURN_URL = ""  # Optional default return_url when not provided in request

# Plan IDs -> Stripe Product IDs (prod_xxx)
STRIPE_PLANS = {
    "starter": "prod_UAb7IngirFX1mo",   # $49/mo
    "pro": "prod_UAb7rv9k8zoPwE",       # $99/mo
    "growth": "prod_UAb7VPi46dLlIo",    # $199/mo
}
# Plan amounts in smallest currency unit (cents); currency per plan
STRIPE_PLAN_AMOUNTS = {
    "starter": 4900,
    "pro": 9900,
    "growth": 19900,
}
STRIPE_PLAN_CURRENCIES = {
    "starter": "usd",
    "pro": "usd",
    "growth": "usd",
}

# WheelPros SFTP: host/port for all connections (override via env). Per-company user/password in
# CompanyProviders.credentials; optional WHEELPROS_SFTP_USER/PASSWORD for local/dev sync only.
WHEELPROS_SFTP_HOST = os.environ.get("WHEELPROS_SFTP_HOST", "sftp.wheelpros.com")
WHEELPROS_SFTP_PORT = int(os.environ.get("WHEELPROS_SFTP_PORT", "22"))
WHEELPROS_SFTP_USER = os.environ.get("WHEELPROS_SFTP_USER", "")
WHEELPROS_SFTP_PASSWORD = os.environ.get("WHEELPROS_SFTP_PASSWORD", "")
WHEELPROS_SFTP_PATH = os.environ.get("WHEELPROS_SFTP_PATH", "CommonFeed/USD/WHEEL/wheelInvPriceData.csv")
WHEELPROS_INVENTORY_LOCAL_PATH = os.environ.get("WHEELPROS_INVENTORY_LOCAL_PATH", "/tmp/wheelpros_wheel_inventory.csv")
WHEELPROS_TIRE_LOCAL_PATH = os.environ.get("WHEELPROS_TIRE_LOCAL_PATH", "/tmp/wheelpros_tire_inventory.csv")
WHEELPROS_ACCESSORIES_LOCAL_PATH = os.environ.get("WHEELPROS_ACCESSORIES_LOCAL_PATH", "/tmp/wheelpros_accessories_inventory.csv")
# Set to False to verify host keys against ~/.ssh/known_hosts (recommended for production).
WHEELPROS_SFTP_AUTO_ADD_HOST_KEY = os.environ.get("WHEELPROS_SFTP_AUTO_ADD_HOST_KEY", "true").lower() in ("true", "1", "yes")

# Meyer relay SFTP: AftermarketMonkey-hosted server; per-company sftp_user/sftp_password in CompanyProviders.
# Env vars (all optional — sensible defaults if unset; use `or` below so empty string does not clear defaults):
#   MEYER_SFTP_HOST, MEYER_SFTP_PORT, MEYER_SFTP_DIRECTORY,
#   MEYER_PRICING_REMOTE_FILE, MEYER_INVENTORY_REMOTE_FILE
try:
    _meyer_port = int(os.environ.get("MEYER_SFTP_PORT") or "22")
except ValueError:
    _meyer_port = 22
MEYER_SFTP_HOST = os.environ.get("MEYER_SFTP_HOST") or "54.145.82.238"
MEYER_SFTP_PORT = _meyer_port if 1 <= _meyer_port <= 65535 else 22
MEYER_SFTP_DIRECTORY = os.environ.get("MEYER_SFTP_DIRECTORY") or "uploads"
MEYER_PRICING_REMOTE_FILE = os.environ.get("MEYER_PRICING_REMOTE_FILE") or "Meyer Pricing.csv"
MEYER_INVENTORY_REMOTE_FILE = os.environ.get("MEYER_INVENTORY_REMOTE_FILE") or "Meyer Inventory.csv"
MEYER_PRICING_LOCAL_PATH = os.environ.get("MEYER_PRICING_LOCAL_PATH", "/tmp/meyer_pricing.csv")
MEYER_INVENTORY_LOCAL_PATH = os.environ.get("MEYER_INVENTORY_LOCAL_PATH", "/tmp/meyer_inventory.csv")

# A-Tech relay SFTP: same pattern as Meyer — per-company sftp_user/sftp_password in CompanyProviders.
try:
    _atech_port = int(os.environ.get("ATECH_SFTP_PORT") or "22")
except ValueError:
    _atech_port = 22
ATECH_SFTP_HOST = os.environ.get("ATECH_SFTP_HOST") or "54.145.82.238"
ATECH_SFTP_PORT = _atech_port if 1 <= _atech_port <= 65535 else 22
ATECH_SFTP_DIRECTORY = os.environ.get("ATECH_SFTP_DIRECTORY") or "uploads"
# Single combined feed: pricing, per-warehouse qty, fees, GTIN (see clients/atech/feed_spec.py).
ATECH_FEED_REMOTE_FILE = os.environ.get("ATECH_FEED_REMOTE_FILE") or "atechfile.txt"
ATECH_FEED_LOCAL_PATH = os.environ.get("ATECH_FEED_LOCAL_PATH", "/tmp/atechfile.txt")

# DLG relay SFTP — inventory CSV (Brand, Name, Display Name, Available On Hand, Units, Base Price).
try:
    _dlg_port = int(os.environ.get("DLG_SFTP_PORT") or "22")
except ValueError:
    _dlg_port = 22
DLG_SFTP_HOST = os.environ.get("DLG_SFTP_HOST") or "54.145.82.238"
DLG_SFTP_PORT = _dlg_port if 1 <= _dlg_port <= 65535 else 22
DLG_SFTP_DIRECTORY = os.environ.get("DLG_SFTP_DIRECTORY") or "uploads"
DLG_INVENTORY_REMOTE_FILE = os.environ.get("DLG_INVENTORY_REMOTE_FILE") or "dlg_inventory.csv"
DLG_INVENTORY_LOCAL_PATH = os.environ.get("DLG_INVENTORY_LOCAL_PATH", "/tmp/dlg_inventory.csv")

# Meilisearch (backend: master key for indexing; FE will use a public read-only key)
MEILISEARCH_HOST = "http://localhost:7700"
MEILISEARCH_MASTER_KEY = ""  # Set via env; required for indexing. Create a separate search-only key for FE.
MEILISEARCH_INDEX_PARTS = "parts"