"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-yn^dlc9j100z&q5x!sx5m4*9z6g-k*zcibu_p3#f(fv=b&yr^z"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["5.161.121.143"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "src",
]

MIGRATION_MODULES = {
    "src": "migrations",
}
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.common.CommonMiddleware",
    #"django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "src.authentication.middleware.JWTAuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:8080',
    'http://localhost:80',
    'http://142.132.187.151:8005',
    'http://142.132.187.151:8007',
    'http://142.132.187.151:8000',
    'http://142.132.187.151:8080',
    'http://142.132.187.151:80',
    'https://142.132.187.151:443',
    'http://49.13.0.20:8005',
    'http://49.13.0.20:8007',
    'http://49.13.0.20:8000',
    'https://shopifyanalytics.netlify.app',
    'http://frontend:8000',
    'http://frontend:8080',
    'http://frontend:80',
    'https://dashboard.crotechflow.com',
    'https://www.dashboard.crotechflow.com',
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = "urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wsgi.application"

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTHENTICATION_BACKENDS = [
    "src.authentication.backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
    },
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(name)s.%(funcName)s:%(lineno)s %(message)s"
        },
    },
}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "<TAG>",
        "USER": "<TAG>",
        "PASSWORD": "<TAG>",
        "HOST": "<TAG>",
        "PORT": "<TAG>",
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "<TAG>",
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
    }
}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "mail.jsoncargo.com"
EMAIL_PORT = 587
EMAIL_USE_SSL = False
EMAIL_HOST_USER = "noreply@jsoncargo.com"
EMAIL_HOST_PASSWORD = "your-email-account-password"  # Replace with the actual password
DEFAULT_FROM_EMAIL = "noreply@jsoncargo.com"

LOGGING_EMAIL_RECIPIENT_LIST = ["hajdukbet@gmail.com"]
SUPPORT_EMAIL_RECIPIENT_LIST = ["hajdukbet@gmail.com"]

# Resend (transactional notification emails, e.g. "first sync completed") — https://resend.com
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")
NOTIFICATIONS_FROM_EMAIL = os.environ.get("NOTIFICATIONS_FROM_EMAIL", "no-reply@aftermarketscout.com")

# Frontend app base URL, used to build links in transactional emails.
FRONTEND_BASE_URL = os.environ.get("FRONTEND_BASE_URL", "https://app.aftermarketscout.com")

TURN14_BASE_URL = 'https://api.turn14.com/v1'

# Turn 14 Electronic Order API (quote/order/status) — separate hosts for their "testing" and
# "production" environments; the "environment" value must also be set to match in every
# request body (per Turn 14's docs: requests to apitest.turn14.com must carry "testing",
# requests to api.turn14.com must carry "production" — the two must always agree). Flipped
# back to testing now that submit is called synchronously, directly from POST .../submit/
# (run_submit_synchronously) instead of behind a job a human runs by hand — testing gives a
# safety margin while that new path gets exercised, since Turn 14's docs confirm even their
# testing environment creates a real (test) order, not a dry-run. Revisit once the
# synchronous submit flow has been validated end-to-end against apitest.turn14.com.
TURN14_ORDER_TEST_BASE_URL = 'https://apitest.turn14.com/v1'
TURN14_ORDER_PRODUCTION_BASE_URL = 'https://api.turn14.com/v1'
TURN14_ORDER_ENVIRONMENT = os.environ.get("TURN14_ORDER_ENVIRONMENT", "testing")

# How long a PurchaseOrder's quote stays valid before submit is blocked and a re-quote is
# required. Distributor pricing/availability can shift between quote and submit; this stops
# a stale quote from being submitted against materially different real-world stock/pricing.
PURCHASE_ORDER_QUOTE_TTL_MINUTES = int(os.environ.get("PURCHASE_ORDER_QUOTE_TTL_MINUTES", "15"))

# Keystone FTP (implicit FTPS, port 990)
KEYSTONE_FTP_HOST = 'ftp.ekeystone.com'
KEYSTONE_FTP_PORT = 990
KEYSTONE_FTP_USER = ''  # Set via env or CompanyProviders.credentials
KEYSTONE_FTP_PASSWORD = ''
KEYSTONE_INVENTORY_LOCAL_PATH = '/tmp/keystone_inventory.csv'

# Keystone Electronic Order Web Service (SOAP order placement) — a single fixed endpoint for
# both test and production use; unlike Turn14, there's no separate host per environment, only a
# different `security_key` value (see CompanyProviders.credentials["order"]).
KEYSTONE_ORDER_ELECTRONIC_ORDER_URL = os.environ.get(
    "KEYSTONE_ORDER_ELECTRONIC_ORDER_URL", "http://order.ekeystone.com/wselectronicorder/electronicorder.asmx"
)

# Rough Country jobber feed (Excel). Override ROUGH_COUNTRY_FEED_URL if the default returns 403.
ROUGH_COUNTRY_FEED_URL = "https://feeds.roughcountry.com/jobber_pc2A.xlsx"

# Stripe (billing portal + checkout)
STRIPE_SECRET_KEY = ""  # Set via env; required for billing
BILLING_PORTAL_RETURN_URL = ""  # Optional default return_url when not provided in request

# Plan IDs -> Stripe Product IDs (prod_xxx)
STRIPE_PLANS = {
    "starter": "prod_UAb7IngirFX1mo",   # $49/mo
    "pro": "prod_UAb7rv9k8zoPwE",       # $99/mo
    "growth": "prod_UAb7VPi46dLlIo",    # $199/mo
}
# Plan amounts in smallest currency unit (cents); currency per plan
STRIPE_PLAN_AMOUNTS = {
    "starter": 4900,
    "pro": 9900,
    "growth": 19900,
}
STRIPE_PLAN_CURRENCIES = {
    "starter": "usd",
    "pro": "usd",
    "growth": "usd",
}

# Stripe webhook signing secret — set via env (STRIPE_WEBHOOK_SECRET)
STRIPE_WEBHOOK_SECRET = ""

# Per-plan feature limits. -1 means unlimited. Searches are always unlimited.
# None key = free/unsubscribed tier.
PLAN_LIMITS = {
    None: {
        "detail_views_per_month": 50,
    },
    "starter": {
        "detail_views_per_month": 500,
    },
    "pro": {
        "detail_views_per_month": 2500,
    },
    "growth": {
        "detail_views_per_month": -1,  # unlimited
    },
}

# WheelPros SFTP: host/port for all connections (override via env). Per-company user/password in
# CompanyProviders.credentials; optional WHEELPROS_SFTP_USER/PASSWORD for local/dev sync only.
WHEELPROS_SFTP_HOST = os.environ.get("WHEELPROS_SFTP_HOST", "sftp.wheelpros.com")
WHEELPROS_SFTP_PORT = int(os.environ.get("WHEELPROS_SFTP_PORT", "22"))
WHEELPROS_SFTP_USER = os.environ.get("WHEELPROS_SFTP_USER", "")
WHEELPROS_SFTP_PASSWORD = os.environ.get("WHEELPROS_SFTP_PASSWORD", "")
WHEELPROS_SFTP_PATH = os.environ.get("WHEELPROS_SFTP_PATH", "CommonFeed/USD/WHEEL/wheelInvPriceData.csv")
WHEELPROS_INVENTORY_LOCAL_PATH = os.environ.get("WHEELPROS_INVENTORY_LOCAL_PATH", "/tmp/wheelpros_wheel_inventory.csv")
WHEELPROS_TIRE_LOCAL_PATH = os.environ.get("WHEELPROS_TIRE_LOCAL_PATH", "/tmp/wheelpros_tire_inventory.csv")
WHEELPROS_ACCESSORIES_LOCAL_PATH = os.environ.get("WHEELPROS_ACCESSORIES_LOCAL_PATH", "/tmp/wheelpros_accessories_inventory.csv")
# Set to False to verify host keys against ~/.ssh/known_hosts (recommended for production).
WHEELPROS_SFTP_AUTO_ADD_HOST_KEY = os.environ.get("WHEELPROS_SFTP_AUTO_ADD_HOST_KEY", "true").lower() in ("true", "1", "yes")

# Wheel Pros Order API (REST, Product Data Portal username/password -> 1hr Bearer JWT via
# POST /auth/v1/authorize) — single host for both "auth" and "orders" API areas; "testing" points
# at Wheel Pros' dev subdomain, same pattern as Turn14/Meyer/Premier's environment split.
WHEELPROS_ORDER_TEST_BASE_URL = os.environ.get("WHEELPROS_ORDER_TEST_BASE_URL", "https://dev.api.wheelpros.com")
WHEELPROS_ORDER_PRODUCTION_BASE_URL = os.environ.get("WHEELPROS_ORDER_PRODUCTION_BASE_URL", "https://api.wheelpros.com")
WHEELPROS_ORDER_ENVIRONMENT = os.environ.get("WHEELPROS_ORDER_ENVIRONMENT", "production")

# Meyer relay SFTP: AftermarketMonkey-hosted server; per-company sftp_user/sftp_password in CompanyProviders.
# Env vars (all optional — sensible defaults if unset; use `or` below so empty string does not clear defaults):
#   MEYER_SFTP_HOST, MEYER_SFTP_PORT, MEYER_SFTP_DIRECTORY,
#   MEYER_PRICING_REMOTE_FILE, MEYER_INVENTORY_REMOTE_FILE
try:
    _meyer_port = int(os.environ.get("MEYER_SFTP_PORT") or "22")
except ValueError:
    _meyer_port = 22
MEYER_SFTP_HOST = os.environ.get("MEYER_SFTP_HOST") or "5.161.121.143"
MEYER_SFTP_PORT = _meyer_port if 1 <= _meyer_port <= 65535 else 22
MEYER_SFTP_DIRECTORY = os.environ.get("MEYER_SFTP_DIRECTORY") or "uploads"
MEYER_PRICING_REMOTE_FILE = os.environ.get("MEYER_PRICING_REMOTE_FILE") or "Meyer Pricing.csv"
MEYER_INVENTORY_REMOTE_FILE = os.environ.get("MEYER_INVENTORY_REMOTE_FILE") or "Meyer Inventory.csv"
MEYER_PRICING_LOCAL_PATH = os.environ.get("MEYER_PRICING_LOCAL_PATH", "/tmp/meyer_pricing.csv")
MEYER_INVENTORY_LOCAL_PATH = os.environ.get("MEYER_INVENTORY_LOCAL_PATH", "/tmp/meyer_inventory.csv")

# Meyer Order API (REST, static Espresso apikey issued directly by a Meyer rep) — separate
# hosts for their "testing" and "production" environments, same pattern as Turn14's order API
# split. Defaults to "testing" for now — flip to "production" (or set MEYER_ORDER_ENVIRONMENT)
# once Meyer order placement has been verified end-to-end against the test API.
MEYER_ORDER_TEST_BASE_URL = os.environ.get(
    "MEYER_ORDER_TEST_BASE_URL", "https://meyerapitest.meyerdistributing.com/http/default/TestAPI/v2"
)
MEYER_ORDER_PRODUCTION_BASE_URL = os.environ.get(
    "MEYER_ORDER_PRODUCTION_BASE_URL", "https://meyerapi.meyerdistributing.com/http/default/ProdAPI/v2"
)
MEYER_ORDER_ENVIRONMENT = os.environ.get("MEYER_ORDER_ENVIRONMENT", "testing")

# A-Tech relay SFTP: same pattern as Meyer — per-company sftp_user/sftp_password in CompanyProviders.
try:
    _atech_port = int(os.environ.get("ATECH_SFTP_PORT") or "22")
except ValueError:
    _atech_port = 22
ATECH_SFTP_HOST = os.environ.get("ATECH_SFTP_HOST") or "5.161.121.143"
ATECH_SFTP_PORT = _atech_port if 1 <= _atech_port <= 65535 else 22
ATECH_SFTP_DIRECTORY = os.environ.get("ATECH_SFTP_DIRECTORY") or "uploads"
# Single combined feed: pricing, per-warehouse qty, fees, GTIN (see clients/atech/feed_spec.py).
ATECH_FEED_REMOTE_FILE = os.environ.get("ATECH_FEED_REMOTE_FILE") or "atechfile.txt"
ATECH_FEED_LOCAL_PATH = os.environ.get("ATECH_FEED_LOCAL_PATH", "/tmp/atechfile.txt")
try:
    ATECH_PRICING_LOOKUP_MAX_WORKERS = int(os.environ.get("ATECH_PRICING_LOOKUP_MAX_WORKERS", "1"))
except ValueError:
    ATECH_PRICING_LOOKUP_MAX_WORKERS = 4
try:
    ATECH_COMPANY_PRICING_SYNC_MAX_WORKERS = int(os.environ.get("ATECH_COMPANY_PRICING_SYNC_MAX_WORKERS", "1"))
except ValueError:
    ATECH_COMPANY_PRICING_SYNC_MAX_WORKERS = 1
try:
    ATECH_PARTS_UPSERT_MAX_WORKERS = int(os.environ.get("ATECH_PARTS_UPSERT_MAX_WORKERS", "1"))
except ValueError:
    ATECH_PARTS_UPSERT_MAX_WORKERS = 4
try:
    ATECH_COMPANY_PRICING_UPSERT_MAX_WORKERS = int(os.environ.get("ATECH_COMPANY_PRICING_UPSERT_MAX_WORKERS", "1"))
except ValueError:
    ATECH_COMPANY_PRICING_UPSERT_MAX_WORKERS = 4
try:
    ATECH_PARSE_PROGRESS_EVERY = int(os.environ.get("ATECH_PARSE_PROGRESS_EVERY", "250000"))
except ValueError:
    ATECH_PARSE_PROGRESS_EVERY = 250000

try:
    MEYER_COMPANY_PRICING_SYNC_MAX_WORKERS = int(os.environ.get("MEYER_COMPANY_PRICING_SYNC_MAX_WORKERS", "2"))
except ValueError:
    MEYER_COMPANY_PRICING_SYNC_MAX_WORKERS = 2
try:
    MEYER_PART_LOOKUP_MAX_WORKERS = int(os.environ.get("MEYER_PART_LOOKUP_MAX_WORKERS", "4"))
except ValueError:
    MEYER_PART_LOOKUP_MAX_WORKERS = 4
try:
    MEYER_PARSE_PROGRESS_EVERY = int(os.environ.get("MEYER_PARSE_PROGRESS_EVERY", "250000"))
except ValueError:
    MEYER_PARSE_PROGRESS_EVERY = 250000

# Relay SFTP account provisioning: creates a dedicated, chrooted SFTP login per company on the
# relay box itself (same server as MEYER_SFTP_HOST/ATECH_SFTP_HOST above), mirroring the manually
# created "thor" account (Linux user in the `sftpusers` group, home under RELAY_SFTP_BASE_DIR,
# relies on sshd's `Match Group sftpusers` block for the chroot — no per-user sshd config needed).
RELAY_SFTP_SSH_HOST = os.environ.get("RELAY_SFTP_SSH_HOST") or "5.161.121.143"
try:
    RELAY_SFTP_SSH_PORT = int(os.environ.get("RELAY_SFTP_SSH_PORT") or "22")
except ValueError:
    RELAY_SFTP_SSH_PORT = 22
RELAY_SFTP_SSH_USER = os.environ.get("RELAY_SFTP_SSH_USER") or "root"
RELAY_SFTP_SSH_PASSWORD = os.environ.get("RELAY_SFTP_SSH_PASSWORD") or ""
RELAY_SFTP_GROUP = os.environ.get("RELAY_SFTP_GROUP") or "sftpusers"
RELAY_SFTP_BASE_DIR = os.environ.get("RELAY_SFTP_BASE_DIR") or "/sftp"

# DLG: relay host/path/file are in ``src.constants``; app-level SFTP login (not per CompanyProvider) — set in env.
DLG_RELAY_SFTP_USER = os.environ.get("DLG_RELAY_SFTP_USER", "")
DLG_RELAY_SFTP_PASSWORD = os.environ.get("DLG_RELAY_SFTP_PASSWORD", "")
# Legacy / ops — not read by DlgSFTPClient (see src.constants for relay; credentials above for auth)
try:
    _dlg_port = int(os.environ.get("DLG_SFTP_PORT") or "22")
except ValueError:
    _dlg_port = 22
DLG_SFTP_HOST = os.environ.get("DLG_SFTP_HOST") or "54.145.82.238"
DLG_SFTP_PORT = _dlg_port if 1 <= _dlg_port <= 65535 else 22
DLG_SFTP_DIRECTORY = os.environ.get("DLG_SFTP_DIRECTORY") or "uploads"
DLG_INVENTORY_REMOTE_FILE = os.environ.get("DLG_INVENTORY_REMOTE_FILE") or "dlg_inventory.csv"
DLG_INVENTORY_LOCAL_PATH = os.environ.get("DLG_INVENTORY_LOCAL_PATH", "/tmp/dlg_inventory.csv")

# ASAP Network: paid catalog API, global token (not per-company — see CompanyProviders docstring
# for why this isn't stored there). No documented rate limit. Lowered from an earlier default of
# 8 concurrent workers after a full-catalog run hit repeated read timeouts - likely us overloading
# their API, not just transient flakiness - so this also caps requests/second on top of
# concurrency (see ASAP_NETWORK_MAX_REQUESTS_PER_SECOND). Paid per call; tune down further if
# timeouts persist, or up once real limits are confirmed.
ASAP_NETWORK_API_TOKEN = os.environ.get("ASAP_NETWORK_API_TOKEN", "")
try:
    ASAP_NETWORK_MAX_CONCURRENT_REQUESTS = int(os.environ.get("ASAP_NETWORK_MAX_CONCURRENT_REQUESTS", "4"))
except ValueError:
    ASAP_NETWORK_MAX_CONCURRENT_REQUESTS = 4
try:
    ASAP_NETWORK_MAX_REQUESTS_PER_SECOND = int(os.environ.get("ASAP_NETWORK_MAX_REQUESTS_PER_SECOND", "5"))
except ValueError:
    ASAP_NETWORK_MAX_REQUESTS_PER_SECOND = 5

# Meilisearch (backend: master key for indexing; FE will use a public read-only key)
MEILISEARCH_HOST = "http://localhost:7700"
MEILISEARCH_MASTER_KEY = ""  # Set via env; required for indexing. Create a separate search-only key for FE.
MEILISEARCH_INDEX_PARTS = "parts"
# Small reference index driving the FE's Year/Make/Model cascading selector via facet search
# (Meilisearch has no "value within range" filter, so this is built from MasterPartFitment
# ranges expanded per-year, same as the parts index's fitment_keys field).
MEILISEARCH_INDEX_VEHICLES = "vehicles"
try:
    MEILISEARCH_REINDEX_BATCH_SIZE = int(os.environ.get("MEILISEARCH_REINDEX_BATCH_SIZE", "5000"))
except ValueError:
    MEILISEARCH_REINDEX_BATCH_SIZE = 5000
try:
    MEILISEARCH_REINDEX_UPLOAD_WORKERS = int(os.environ.get("MEILISEARCH_REINDEX_UPLOAD_WORKERS", "4"))
except ValueError:
    MEILISEARCH_REINDEX_UPLOAD_WORKERS = 4

# Premier (APG Wholesale) Order API (REST, apiKey -> Bearer JWT session token) — separate hosts
# for their "testing" and "production" environments. Note the test host is plain HTTP, not
# HTTPS, per Premier's own docs.
PREMIER_ORDER_TEST_BASE_URL = os.environ.get("PREMIER_ORDER_TEST_BASE_URL", "http://api-test.premierwd.com/api/v5")
PREMIER_ORDER_PRODUCTION_BASE_URL = os.environ.get(
    "PREMIER_ORDER_PRODUCTION_BASE_URL", "https://api.premierwd.com/api/v5"
)
PREMIER_ORDER_ENVIRONMENT = os.environ.get("PREMIER_ORDER_ENVIRONMENT", "production")