from django.contrib import admin
from django.urls import path, include
from src.api.views.authentication import LoginView, ChangePasswordView
from src.api.views.company import CompanyDestinationsView
from src.api.views.integrations import (
    ProvidersCatalogView,
    ProviderConnectView,
    ProviderConnectionView,
    ProviderConnectionDetailView,
    CompanyProvidersView,
    CompanyProviderDetailView,
    BrandsWithProvidersView,
    CompanyDestinationsWithBrandsView,
    CompanyDestinationDetailView,
    ExecutionRunsView,
    ExecutionRunPartsHistoryView,
)
from src.api.views.company_settings import (
    ProfileView,
    CompanySettingsView,
    CompanyTeamView,
    CompanyTeamMemberView,
)
from src.api.views.billing import (
    CreatePortalSessionView,
    CreateCheckoutSessionView,
    SubscriptionView,
)
from src.api.views.onboarding import (
    RegisterView,
    CompanyDetailsView,
    PersonalizationView,
    OnboardingStatusView,
    DistributorCredentialsInfoView,
)
from src.api.views.parts import (
    MasterPartBrandsForFilterView,
    MasterPartCategoryFiltersView,
    PartAuditCompanyHistoryView,
    PartAuditMyHistoryView,
    PartDetailView,
    PartsSearchView,
)
from src.api.views.turn14_locations import Turn14LocationsView

urlpatterns = [
    path(
        "auth/login/",
        LoginView.as_view(),
        name="login"
    ),
    path(
        "onboarding/register/",
        RegisterView.as_view(),
        name="onboarding_register",
    ),
    path(
        "onboarding/company-details/",
        CompanyDetailsView.as_view(),
        name="onboarding_company_details",
    ),
    path(
        "onboarding/personalization/",
        PersonalizationView.as_view(),
        name="onboarding_personalization",
    ),
    path(
        "onboarding/status/",
        OnboardingStatusView.as_view(),
        name="onboarding_status",
    ),
    path(
        "onboarding/distributor-credentials-info/",
        DistributorCredentialsInfoView.as_view(),
        name="onboarding_distributor_credentials_info",
    ),
    path(
        "auth/change-password/",
        ChangePasswordView.as_view(),
        name="change_password"
    ),
    path(
        "auth/company/destinations/",
        CompanyDestinationsView.as_view(),
        name="company_destinations",
    ),
    path(
        "integrations/catalog/",
        ProvidersCatalogView.as_view(),
        name="providers_catalog",
    ),
    path(
        "integrations/catalog/<int:id>/connect/",
        ProviderConnectView.as_view(),
        name="provider_connect",
    ),
    path(
        "integrations/connections/<int:company_provider_id>/detail/",
        ProviderConnectionDetailView.as_view(),
        name="provider_connection_detail",
    ),
    path(
        "integrations/connections/<int:company_provider_id>/",
        ProviderConnectionView.as_view(),
        name="provider_connection",
    ),
    path(
        "company-providers/",
        CompanyProvidersView.as_view(),
        name="company_providers",
    ),
    path(
        "company-providers/<int:id>/",
        CompanyProviderDetailView.as_view(),
        name="company_provider_detail",
    ),
    path(
        "brands/",
        BrandsWithProvidersView.as_view(),
        name="brands_with_providers",
    ),
    path(
        "destinations/",
        CompanyDestinationsWithBrandsView.as_view(),
        name="company_destinations_with_brands",
    ),
    path(
        "destinations/<int:id>/",
        CompanyDestinationDetailView.as_view(),
        name="company_destination_detail",
    ),
    path(
        "execution-runs/",
        ExecutionRunsView.as_view(),
        name="execution_runs",
    ),
    path(
        "execution-runs/<int:destination_id>/",
        ExecutionRunsView.as_view(),
        name="execution_runs_by_destination",
    ),
    path(
        "execution-runs/<int:execution_run_id>/parts-history/",
        ExecutionRunPartsHistoryView.as_view(),
        name="execution_run_parts_history",
    ),
    path(
        "parts/search/",
        PartsSearchView.as_view(),
        name="parts_search",
    ),
    path(
        "parts/search/brands/",
        MasterPartBrandsForFilterView.as_view(),
        name="parts_search_brands",
    ),
    path(
        "parts/search/categories/",
        MasterPartCategoryFiltersView.as_view(),
        name="parts_search_categories",
    ),
    path(
        "parts/audit/me/",
        PartAuditMyHistoryView.as_view(),
        name="parts_audit_me",
    ),
    path(
        "parts/audit/company/",
        PartAuditCompanyHistoryView.as_view(),
        name="parts_audit_company",
    ),
    path(
        "parts/<int:id>/",
        PartDetailView.as_view(),
        name="part_detail",
    ),
    path(
        "turn14/locations/",
        Turn14LocationsView.as_view(),
        name="turn14_locations",
    ),
    path(
        "settings/profile/",
        ProfileView.as_view(),
        name="profile",
    ),
    path(
        "settings/company/",
        CompanySettingsView.as_view(),
        name="company_settings",
    ),
    path(
        "settings/company/team/",
        CompanyTeamView.as_view(),
        name="company_team",
    ),
    path(
        "settings/company/team/<int:user_id>/",
        CompanyTeamMemberView.as_view(),
        name="company_team_member",
    ),
    path(
        "billing/subscription/",
        SubscriptionView.as_view(),
        name="billing_subscription",
    ),
    path(
        "billing/create-portal-session/",
        CreatePortalSessionView.as_view(),
        name="billing_create_portal_session",
    ),
    path(
        "billing/create-checkout-session/",
        CreateCheckoutSessionView.as_view(),
        name="billing_create_checkout_session",
    ),
]