"""
Standalone script — no Django required.
Checks if lead websites are live using Storm proxies and updates the DB directly.

Run on the server:
  python3 validate_websites_standalone.py

Requirements:
  pip3 install psycopg2-binary requests
"""
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from urllib.parse import quote

import psycopg2
import psycopg2.extras
import requests

# ------------------------------------------------------------------
# Config
# ------------------------------------------------------------------
DB_HOST     = "5.161.121.143"
DB_PORT     = 5432
DB_NAME     = "aftermarketmonkey-db"
DB_USER     = "aftermarketmonkey_admin"
DB_PASSWORD = "%UUqiucpRIdg1XWx"

PROXY_GATEWAY  = "37.48.118.90:13081"
PROXY_USER     = "jsoncargo@gmail.com"
PROXY_PASSWORD = "ndx1wbh0erj.fyv1PAR"

WORKERS    = 20     # proxy handles ~20 concurrent connections comfortably
BATCH_SIZE = 100
TIMEOUT    = 20     # longer timeout for sites with security checks/challenges
RETRY_WAIT = 2      # seconds to wait before retrying a proxy error
MAX_RETRIES = 2
HEADERS    = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    ),
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Encoding": "gzip, deflate, br",
    "Connection": "keep-alive",
    "Upgrade-Insecure-Requests": "1",
}

# Status codes that unconditionally mean the site is live (auth wall, rate limit)
LIVE_DESPITE_ERROR_CODES = {401, 406, 429}

# Security/bot-protection platforms that return 403/503 but site is actually live
SECURITY_SERVER_SIGNATURES = {
    "cloudflare", "sucuri", "incapsula", "imperva",
    "ddos-guard", "blazingfast", "akamai", "fastly",
    "amazons3", "cloudfront",
}

# Body snippets that indicate a CDN/proxy geo-block — site is live, just our IP is blocked
GEO_BLOCK_BODY_SIGNATURES = [
    "generated by cloudfront",
    "request could not be satisfied",
    "configured to block access from your country",
    "access denied",
    "error from cloudfront",
    "x-cache: error from cloudfront",
]

# ------------------------------------------------------------------
# Proxy setup
# ------------------------------------------------------------------
_user = quote(PROXY_USER, safe="")
_pass = quote(PROXY_PASSWORD, safe="")
PROXIES = {
    "http":  f"http://{_user}:{_pass}@{PROXY_GATEWAY}",
    "https": f"http://{_user}:{_pass}@{PROXY_GATEWAY}",
}

# ------------------------------------------------------------------
# Website check
# ------------------------------------------------------------------
def _is_security_wall(resp) -> bool:
    """True if a 403/503 comes from a security platform or geo-block — site is actually live."""
    server = resp.headers.get("server", "").lower()
    via = resp.headers.get("via", "").lower()

    # Known CDN/WAF in server or via header
    if any(sig in server for sig in SECURITY_SERVER_SIGNATURES):
        return True
    if any(sig in via for sig in SECURITY_SERVER_SIGNATURES):
        return True

    # Cloudflare-specific header
    if "cf-ray" in resp.headers:
        return True

    # CloudFront geo-block or access denied — check body snippet
    try:
        body = resp.text.lower()
        if any(sig in body for sig in GEO_BLOCK_BODY_SIGNATURES):
            return True
    except Exception:
        pass

    return False


def _is_live(resp) -> bool:
    """True if the response means the site is up."""
    code = resp.status_code
    if code < 400:
        return True
    if code in LIVE_DESPITE_ERROR_CODES:
        return True
    # 403 or 503 only counts as live if it's from a security platform
    if code in (403, 503) and _is_security_wall(resp):
        return True
    return False


def _do_request(url: str, proxies: dict) -> tuple[bool, int | None]:
    """Returns (is_live, status_code). Raises on connection error."""
    resp = requests.head(url, timeout=TIMEOUT, headers=HEADERS, allow_redirects=True, proxies=proxies)

    # HEAD not supported — retry as GET
    if resp.status_code in (405, 501):
        resp = requests.get(url, timeout=TIMEOUT, headers=HEADERS, allow_redirects=True, stream=True, proxies=proxies)
        resp.close()

    return _is_live(resp), resp.status_code


def check(lead_id: int, url: str) -> tuple:
    """Returns (lead_id, is_live, status_code, error).
    Retries proxy errors up to MAX_RETRIES times, then falls back to direct."""
    last_error = None

    # Try with proxy (with retries)
    for attempt in range(1, MAX_RETRIES + 2):  # +2: initial + retries
        try:
            live, code = _do_request(url, PROXIES)
            return lead_id, live, code, None
        except requests.exceptions.Timeout:
            return lead_id, False, None, "Timeout"
        except requests.exceptions.ProxyError as e:
            last_error = f"ProxyError (attempt {attempt}): {e}"
            if attempt <= MAX_RETRIES:
                time.sleep(RETRY_WAIT)
                continue
            break
        except requests.exceptions.ConnectionError as e:
            error_str = str(e)
            # If the connection error is about the proxy itself, retry
            if "ProxyError" in error_str or "37.48.118.90" in error_str:
                last_error = f"ProxyConnectionError (attempt {attempt})"
                if attempt <= MAX_RETRIES:
                    time.sleep(RETRY_WAIT)
                    continue
                break
            # Otherwise it's the target site that's down — no point retrying
            return lead_id, False, None, f"ConnectionError: {e}"
        except Exception as e:
            return lead_id, False, None, str(e)

    # Proxy failed after all retries — fall back to direct connection
    try:
        live, code = _do_request(url, proxies={})
        return lead_id, live, code, f"proxy_failed_used_direct"
    except requests.exceptions.Timeout:
        return lead_id, False, None, f"Timeout (direct, proxy_failed)"
    except Exception as e:
        return lead_id, False, None, f"proxy_failed + direct_error: {e}"


# ------------------------------------------------------------------
# Bulk DB update
# ------------------------------------------------------------------
def bulk_update(conn, batch: list[tuple]):
    live_ids = [r[0] for r in batch if r[1]]
    dead_ids = [r[0] for r in batch if not r[1]]
    with conn.cursor() as cur:
        if live_ids:
            cur.execute(
                "UPDATE lead SET website_live = TRUE WHERE id = ANY(%s)",
                (live_ids,)
            )
        if dead_ids:
            cur.execute(
                "UPDATE lead SET website_live = FALSE WHERE id = ANY(%s)",
                (dead_ids,)
            )
    conn.commit()


# ------------------------------------------------------------------
# Main
# ------------------------------------------------------------------
def main():
    print(f"Connecting to {DB_HOST}/{DB_NAME}...")
    conn = psycopg2.connect(
        host=DB_HOST, port=DB_PORT, dbname=DB_NAME,
        user=DB_USER, password=DB_PASSWORD,
        connect_timeout=10,
    )

    with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
        cur.execute("""
            SELECT id, website
            FROM lead
            WHERE website IS NOT NULL
              AND website <> ''
              AND website_live IS NULL
        """)
        leads = cur.fetchall()

    total = len(leads)
    print(f"Found {total} leads with a website.")
    print(f"Proxy: {PROXY_USER}@{PROXY_GATEWAY}")
    print(f"Workers: {WORKERS}  Batch size: {BATCH_SIZE}  Retries: {MAX_RETRIES}\n")

    live_count = 0
    dead_count = 0
    proxy_fallback_count = 0
    pending: list[tuple] = []

    with ThreadPoolExecutor(max_workers=WORKERS) as executor:
        futures = {executor.submit(check, row["id"], row["website"]): row for row in leads}

        for i, future in enumerate(as_completed(futures), 1):
            row = futures[future]
            try:
                lead_id, live, status_code, error = future.result()
            except Exception as e:
                lead_id, live, status_code, error = row["id"], False, None, str(e)

            via = ""
            if error == "proxy_failed_used_direct":
                proxy_fallback_count += 1
                via = " [direct fallback]"

            if live:
                live_count += 1
                print(f"  [{i}/{total}] LIVE  ({status_code}){via}  {row['website']}")
            else:
                dead_count += 1
                detail = f"status={status_code}" if status_code else (error or "unknown")
                print(f"  [{i}/{total}] DEAD  ({detail}){via}  {row['website']}")

            pending.append((lead_id, live, status_code, error))

            if len(pending) >= BATCH_SIZE:
                bulk_update(conn, pending)
                print(f"  -- flushed {len(pending)} records to DB --")
                pending.clear()

    if pending:
        bulk_update(conn, pending)
        print(f"  -- flushed {len(pending)} records to DB --")

    conn.close()
    print(f"\nDone.")
    print(f"  Live:           {live_count}")
    print(f"  Dead:           {dead_count}")
    print(f"  Proxy fallback: {proxy_fallback_count}")
    print(f"  Total:          {total}")


if __name__ == "__main__":
    main()
