# Field priority configuration for merging CATALOG and DISTRIBUTOR parts
# Each field maps to its primary source (CATALOG or DISTRIBUTOR)
# If field is null/empty in primary source, fallback to the other source
# Fields not listed default to CATALOG priority

BIGCOMMERCE_PART_FIELD_PRIORITY = {
    'brand_id': 'CATALOG',
    'product_title': 'CATALOG',
    'sku': 'DISTRIBUTOR',
    'mpn': 'CATALOG',
    'description': 'CATALOG',
    'images': 'DISTRIBUTOR',
    'custom_fields': 'CATALOG',
    'active': 'CATALOG',
    'default_price': 'DISTRIBUTOR',
    'cost': 'DISTRIBUTOR',
    'msrp': 'DISTRIBUTOR',
    'weight': 'DISTRIBUTOR',
    'width': 'DISTRIBUTOR',
    'height': 'DISTRIBUTOR',
    'depth': 'DISTRIBUTOR',
    'inventory': 'DISTRIBUTOR',
    'category': 'CATALOG',
    'subcategory': 'CATALOG',
}

# Mapping from Turn14 (category, subcategory) to PCDB (category, subcategory)
# Maps Turn14 category/subcategory pairs to their PCDB equivalents
TURN14_TO_PCDB_CATEGORY_MAP = {
    ("Deflectors", "Window Vents"): ("Exterior Accessories", "Window Deflectors"),
    ("Body Armor & Protection", "Skid Plates"): ("Exterior Protection", "Skid Plates"),
    ("Engine Components", "Gasket Kits"): ("Engine", "Gasket Sets"),
    ("Drivetrain", "Clutch Rebuild Kits"): ("Drivetrain", "Clutch Kits"),
    ("Suspension", "Suspension Controllers"): ("Suspension", "Suspension Electronics"),
    ("Engine Components", "Piston Sets - Powersports"): ("Engine Internal", "Pistons"),
    ("Suspension", "Fork Springs"): ("Suspension", "Springs"),
    ("Suspension", "Control Arms"): ("Suspension", "Control Arms"),
    ("Marketing", "POP Displays"): ("Merchandising", "Point of Purchase Displays"),
    ("Windshields", "Window Shades"): ("Exterior Accessories", "Window Shades"),
    ("Engine Components", "Valves"): ("Engine Internal", "Valves"),
    ("Drivetrain", "Clutch Covers"): ("Drivetrain", "Clutch Components"),
    ("Engine Components", "Bearings"): ("Engine Internal", "Bearings"),
    ("Engine Components", "Engines"): ("Engine", "Complete Engines"),
    ("Suspension", "Steering Stabilizer"): ("Steering", "Steering Stabilizers"),
    ("Engine Components", "Piston Sets - Forged - 5cyl"): ("Engine Internal", "Pistons"),
    ("Apparel", "Shirts"): ("Apparel", "Shirts"),
    ("Engine Components", "Head Gaskets"): ("Engine", "Head Gaskets"),
    ("Lights", "Work Lights"): ("Lighting", "Work Lights"),
    ("Roofs & Roof Accessories", "Chase Racks"): ("Exterior Accessories", "Chase Racks"),
    ("Engine Components", "Hardware - Singles"): ("Engine", "Hardware"),
    ("Suspension", "Alignment Kits"): ("Suspension", "Alignment Components"),
    ("Suspension", "Coilovers"): ("Suspension", "Coilover Kits"),
    ("Suspension", "Bump Stops"): ("Suspension", "Bump Stops"),
    ("Deflectors", "Hood Deflectors"): ("Exterior Accessories", "Hood Deflectors"),
    ("Lights", "Fog Lights"): ("Lighting", "Fog Lights"),
    ("Engine Components", "Piston Coating"): ("Engine Internal", "Piston Accessories"),
    ("Winches & Hitches", "Winch Accessories"): ("Winches", "Winch Accessories"),
    ("Suspension", "Tie Rods"): ("Steering", "Tie Rods"),
    ("Drivetrain", "Clutch Kits - Single"): ("Drivetrain", "Clutch Kits"),
    ("Suspension", "Coilover Components"): ("Suspension", "Coilover Components"),
    ("Engine Components", "Piston Rings"): ("Engine Internal", "Piston Rings"),
    ("Engine Components", "Piston Sets - Custom"): ("Engine Internal", "Pistons"),
    ("Nerf Bars & Running Boards", "Running Boards"): ("Exterior Accessories", "Running Boards"),
    ("Drivetrain", "Pressure Plates"): ("Drivetrain", "Clutch Pressure Plates"),
    ("Bumpers, Grilles & Guards", "Bumper Beams"): ("Body", "Bumper Reinforcements"),
    ("Brakes, Rotors & Pads", "Brake Line Kits"): ("Brakes", "Brake Lines"),
    ("Wheel and Tire Accessories", "Spare Tire Carriers"): ("Exterior Accessories", "Spare Tire Carriers"),
    ("Suspension", "Subframes"): ("Suspension", "Subframes"),
    ("Suspension", "Chassis Bracing"): ("Suspension", "Chassis Bracing"),
    ("Suspension", "Air Compressors"): ("Suspension", "Air Compressors"),
    ("Body Armor & Protection", "Body Armor & Rock Rails"): ("Exterior Protection", "Rock Sliders"),
    ("Drivetrain", "Axles"): ("Drivetrain", "Axle Shafts"),
    ("Lights", "Headlights"): ("Lighting", "Headlights"),
    ("Suspension", "Lift Springs"): ("Suspension", "Lift Springs"),
    ("Lights", "Sidemarkers & Indicators"): ("Lighting", "Side Marker Lights"),
    ("Drivetrain", "Diff Covers"): ("Drivetrain", "Differential Covers"),
    ("Suspension", "Lift Kits"): ("Suspension", "Lift Kits"),
    ("Fuel Delivery", "Fuel Tanks"): ("Fuel System", "Fuel Tanks"),
    ("Engine Components", "Pistons - Custom - Single"): ("Engine Internal", "Pistons"),
    ("Winches & Hitches", "Hitch Receivers"): ("Towing", "Hitch Receivers"),
    ("Lights", "Tail Lights"): ("Lighting", "Tail Lights"),
    ("Suspension", "Coilover Springs"): ("Suspension", "Springs"),
    ("Suspension", "Steering Knuckles & Spindles"): ("Steering", "Steering Knuckles"),
    ("Suspension", "Steering Dampers"): ("Steering", "Steering Dampers"),
    ("Floor Mats", "Floor Mats - Rubber"): ("Interior Accessories", "Floor Mats"),
    ("Truck Bed Accessories", "Cargo Organization"): ("Truck Bed", "Cargo Management"),
    ("Fuel Delivery", "Fuel Systems"): ("Fuel System", "Fuel System Kits"),
    ("Drivetrain", "Clutch Baskets"): ("Drivetrain", "Clutch Components"),
    ("Nerf Bars & Running Boards", "Side Steps"): ("Exterior Accessories", "Side Steps"),
    ("Suspension", "OE Replacement Springs"): ("Suspension", "Replacement Springs"),
    ("Suspension", "Sway Bar Endlinks"): ("Suspension", "Sway BCar End Links"),
    ("Exterior Styling", "Stickers/Decals/Banners"): ("Exterior Accessories", "Decals & Graphics"),
    ("Drivetrain", "Spindles"): ("Drivetrain", "Spindles"),
    ("Roofs & Roof Accessories", "Roofs"): ("Exterior Accessories", "Roof Panels"),
    ("Exterior Styling", "Exterior Trim"): ("Body", "Exterior Trim"),
    ("Engine Components", "Wiring Harnesses"): ("Electrical", "Wiring Harnesses"),
    ("Suspension", "Air Tank Components"): ("Suspension", "Air Suspension Components"),
    ("Drivetrain", "Transmission Mounts"): ("Drivetrain", "Transmission Mounts"),
    ("Suspension", "Shock Mounts & Camber Plates"): ("Suspension", "Shock Mounts"),
    ("Winches & Hitches", "Recovery Boards"): ("Recovery", "Traction Boards"),
    ("Engine Components", "Piston Sets - Forged - 6cyl"): ("Engine Internal", "Pistons"),
    ("Suspension", "Air Springs"): ("Suspension", "Air Springs"),
    ("Suspension", "Shock & Spring Kits"): ("Suspension", "Shock and Spring Kits"),
    ("Engine Components", "Piston Pins"): ("Engine Internal", "Piston Pins"),
    ("Exterior Styling", "Fenders"): ("Body", "Fenders"),
    ("Suspension", "Sway Bars"): ("Suspension", "Sway Bars"),
    ("Bumpers, Grilles & Guards", "Grilles"): ("Body", "Grilles"),
    ("Exterior Styling", "Antennas"): ("Exterior Accessories", "Antennas"),
    ("Exterior Styling", "Doors"): ("Body", "Doors"),
    ("Engine Components", "Valve Covers"): ("Engine", "Valve Covers"),
    ("Wheel and Tire Accessories", "Wheel Spacers & Adapters"): ("Wheels", "Wheel Spacers"),
    ("Roofs & Roof Accessories", "Roof Rack"): ("Exterior Accessories", "Roof Racks"),
    ("Drivetrain", "Clutch Discs"): ("Drivetrain", "Clutch Discs"),
    ("Winches & Hitches", "Winch Kit"): ("Winches", "Winches"),
    ("Interior Accessories", "Shift Knobs"): ("Interior Accessories", "Shift Knobs"),
    ("Suspension", "Traction Bars"): ("Suspension", "Traction Bars"),
    ("Nerf Bars & Running Boards", "Bed Steps"): ("Truck Bed", "Bed Steps"),
    ("Apparel", "Headwear"): ("Apparel", "Headwear"),
    ("Lights", "Light Covers and Guards"): ("Lighting", "Light Covers"),
    ("Suspension", "Lowering Kits"): ("Suspension", "Lowering Kits"),
    ("Truck Bed Accessories", "Bed Racks"): ("Truck Bed", "Bed Racks"),
    ("Wheel and Tire Accessories", "Lug Nuts"): ("Wheels", "Lug Nuts"),
    ("Safety", "Fire Safety"): ("Safety", "Fire Safety"),
    ("Suspension", "Lowering Springs"): ("Suspension", "Lowering Springs"),
    ("Suspension", "Air Tanks"): ("Suspension", "Air Suspension Tanks"),
    ("Roofs & Roof Accessories", "Cargo Boxes & Bags"): ("Exterior Accessories", "Cargo Boxes"),
    ("Exterior Styling", "Hoods"): ("Body", "Hoods"),
    ("Suspension", "Shackle Kits"): ("Suspension", "Leaf Spring Shackles"),
    ("Engine Components", "Piston Pin Locks"): ("Engine Internal", "Piston Pin Locks"),
    ("Apparel", "Keychains"): ("Merchandise", "Keychains"),
    ("Exterior Styling", "License Plate Relocation"): ("Exterior Accessories", "License Plate Brackets"),
    ("Engine Components", "Timing Chains"): ("Engine", "Timing Chains"),
    ("Engine Components", "Hardware Kits - Other"): ("Engine", "Hardware Kits"),
    ("Suspension", "Shocks and Struts"): ("Suspension", "Shocks and Struts"),
    ("Suspension", "Leveling Kits"): ("Suspension", "Leveling Kits"),
    ("Interior Accessories", "Dash & Interior Trim"): ("Interior Accessories", "Interior Trim"),
    ("Suspension", "Leaf Springs & Accessories"): ("Suspension", "Leaf Springs"),
    ("Data Acquisition", "Data Acquisition"): ("Electronics", "Data Acquisition"),
    ("Suspension", "Sway Bar Brackets"): ("Suspension", "Sway Bar Components"),
    ("Truck Bed Accessories", "Bed Bars"): ("Truck Bed", "Bed Bars"),
    ("Interior Accessories", "Relays"): ("Electrical", "Relays"),
    ("Suspension", "Spring Insulators"): ("Suspension", "Spring Insulators"),
    ("Lights", "Bulbs"): ("Lighting", "Light Bulbs"),
    ("Brakes, Rotors & Pads", "Brake Adapters"): ("Brakes", "Brake Adapters"),
    ("Forced Induction", "Intercoolers"): ("Forced Induction", "Intercoolers"),
    ("Fabrication", "Fuel Lines"): ("Fuel System", "Fuel Lines"),
    ("Interior Accessories", "Pedal Covers"): ("Interior Accessories", "Pedal Covers"),
    ("Programmers & Chips", "Switch Panels"): ("Electronics", "Switch Panels"),
    ("Drivetrain", "Driveshafts"): ("Drivetrain", "Driveshafts"),
    ("Suspension", "Ball Joints"): ("Suspension", "Ball Joints"),
    ("Gauges & Pods", "Gauges"): ("Interior Accessories", "Gauges"),
    ("Suspension", "Suspension Arms & Components"): ("Suspension", "Suspension Arms"),
    ("Interior Accessories", "Dash Mounts"): ("Interior Accessories", "Dash Mounts"),
    ("Lights", "Light Accessories and Wiring"): ("Lighting", "Lighting Accessories"),
    ("Engine Components", "Crankshafts"): ("Engine Internal", "Crankshafts"),
    ("Body Armor & Protection", "Mud Flaps"): ("Exterior Accessories", "Mud Flaps"),
    ("Bumpers, Grilles & Guards", "Bumpers - Steel"): ("Body", "Bumpers"),
    ("Fabrication", "Filler Necks"): ("Fuel System", "Filler Necks"),
    ("Exhaust, Mufflers & Tips", "Exhaust Valve Controllers"): ("Exhaust", "Exhaust Electronics"),
    ("Suspension", "Panhard Bars"): ("Suspension", "Panhard Bars"),
    ("Suspension", "Suspension Packages"): ("Suspension", "Suspension Kits"),
    ("Fabrication", "Brackets"): ("Fabrication", "Mounting Brackets"),
    ("Suspension", "Boots"): ("Suspension", "Protective Boots"),
    ("Lights", "Light Bars & Cubes"): ("Lighting", "Light Bars"),
    ("Engine Components", "Piston Sets - Forged - 8cyl"): ("Engine Internal", "Pistons"),
    ("Suspension", "Camber Kits"): ("Suspension", "Camber Kits"),
    ("Truck Bed Accessories", "Truck Bed Rail Protectors"): ("Truck Bed", "Bed Rail Protectors"),
    ("Fabrication", "Clamps"): ("Fabrication", "Clamps"),
    ("Exhaust, Mufflers & Tips", "Exhaust Hardware"): ("Exhaust", "Exhaust Hardware"),
    ("Suspension", "Steering Racks"): ("Steering", "Steering Racks"),
    ("Engine Components", "Wiring Connectors"): ("Electrical", "Electrical Connectors"),
    ("Drivetrain", "Diff Braces"): ("Drivetrain", "Differential Braces"),
    ("Suspension", "Air Suspension Kits"): ("Suspension", "Air Suspension Kits"),
    ("Engine Components", "Piston Sets - Forged - 4cyl"): ("Engine Internal", "Pistons"),
    ("Exterior Styling", "Hood Pins"): ("Exterior Accessories", "Hood Pins"),
    ("Suspension", "Bushing Kits"): ("Suspension", "Bushing Kits"),
    ("Bumpers, Grilles & Guards", "Bumper Accessories"): ("Body", "Bumper Accessories"),
    ("Suspension", "Air Compressor Systems"): ("Suspension", "Air Compressor Systems"),
    ("Engine Components", "Engine Hardware"): ("Engine", "Engine Hardware"),
    ("Body Armor & Protection", "Wheel Well Liners"): ("Exterior Protection", "Wheel Well Liners"),
    ("Truck Bed Accessories", "Bed Liners"): ("Truck Bed", "Bed Liners"),
    ("Oils & Oil Filters", "Hydraulic Oils"): ("Fluids", "Hydraulic Fluid"),
    ("Uncategorized", "Uncategorized"): ("Miscellaneous", "Uncategorized"),
    ("Lights", "Light Mounts"): ("Lighting", "Light Mounts"),
    ("Suspension", "Suspension Arm Bushings"): ("Suspension", "Control Arm Bushings"),
    ("Engine Components", "Pistons - Forged - Single"): ("Engine Internal", "Pistons"),
    ("Fuel Delivery", "Fuel Caps"): ("Fuel System", "Fuel Caps"),
    ("Fender Flares & Trim", "Fender Flares"): ("Exterior Accessories", "Fender Flares"),
    ("Truck Bed Accessories", "Tailgate Accessories"): ("Truck Bed", "Tailgate Accessories"),
    ("Tools", "Tools"): ("Tools", "Automotive Tools"),
    ("Exterior Styling", "Tool Storage"): ("Exterior Accessories", "Tool Storage"),
    ("Truck Bed Accessories", "Truck Bed Cover Replacement Parts"): ("Truck Bed", "Tonneau Covers"),
    ("Truck Bed Accessories", "Cargo Tie-Downs"): ("Truck Bed", "Cargo Tie-Downs"),
    ("Exhaust, Mufflers & Tips", "Catback"): ("Exhaust", "Cat-Back Systems"),
    ("Lights", "Interior Lighting"): ("Lighting", "Interior Lighting"),
    ("Tonneau Covers", "Bed Covers - Folding"): ("Truck Bed", "Tonneau Covers"),
    ("Programmers & Chips", "Programmer Accessories"): ("Electronics", "Programmer Accessories"),
    ("Fabrication", "Hoses"): ("Fabrication", "Hoses"),
    ("Tonneau Covers", "Bed Caps"): ("Truck Bed", "Tonneau Covers"),
    ("Suspension", "Fork Cartridge Kits"): ("Suspension", "Fork Components"),
    ("Exhaust, Mufflers & Tips", "Tips"): ("Exhaust", "Exhaust Tips"),
    ("Forced Induction", "Turbochargers"): ("Forced Induction", "Turbochargers"),
    ("Exhaust, Mufflers & Tips", "Connecting Pipes"): ("Exhaust", "Exhaust Pipes"),
    ("Bumpers, Grilles & Guards", "Grille Guards"): ("Body", "Grille Guards"),
    ("Tonneau Covers", "Tonneau Covers - Retractable"): ("Truck Bed", "Tonneau Covers"),
    ("Roofs & Roof Accessories", "Storage Racks"): ("Exterior Accessories", "Roof Racks"),
    ("Fabrication", "Fittings"): ("Fabrication", "Fittings"),
    ("Wheels", "Wheels - Cast"): ("Wheels", "Wheels"),
    ("Truck Bed Accessories", "Truck Boxes & Storage"): ("Truck Bed", "Storage Boxes"),
    ("Fabrication", "Heat Shields"): ("Fabrication", "Heat Shields"),
    ("Exterior Styling", "Spray Bottles"): ("Exterior Accessories", "Cleaning Supplies"),
    ("Exhaust, Mufflers & Tips", "Resonators"): ("Exhaust", "Resonators"),
    ("Air Intake Systems", "Air Intake Components"): ("Air Intake", "Air Intake Components"),
    ("Suspension", "Caster Kits"): ("Suspension", "Caster Kits"),
    ("Tonneau Covers", "Bed Covers - Hinged"): ("Truck Bed", "Tonneau Covers"),
    ("Fuel Delivery", "Fuel Pumps"): ("Fuel System", "Fuel Pumps"),
    ("Exhaust, Mufflers & Tips", "Muffler"): ("Exhaust", "Mufflers"),
    ("Engine Components", "Mass Air Flow Sensors"): ("Engine", "Mass Air Flow Sensors"),
    ("Exhaust, Mufflers & Tips", "X Pipes"): ("Exhaust", "X-Pipes"),
    ("Exhaust, Mufflers & Tips", "Headers & Manifolds"): ("Exhaust", "Headers"),
    ("Programmers & Chips", "Programmers & Tuners"): ("Electronics", "Programmers & Tuners"),
    ("Programmers & Chips", "In-Line Modules"): ("Electronics", "Performance Modules"),
    ("Tonneau Covers", "Bed Covers - Roll Up"): ("Truck Bed", "Tonneau Covers"),
    ("Marketing", "Marketing"): ("Merchandising", "Marketing Materials"),
    ("Lights", "Light Strip LED"): ("Lighting", "LED Light Strips"),
    ("Wheel and Tire Accessories", "Wheel Center Caps"): ("Wheels", "Center Caps"),
    ("Fabrication", "Steel Tubing"): ("Fabrication", "Steel Tubing"),
    ("Truck Bed Accessories", "Truck Bed Rack"): ("Truck Bed", "Bed Racks"),
    ("Air Intake Systems", "Scoops & Snorkels"): ("Air Intake", "Air Intake Scoops"),
    ("Tonneau Covers", "Tonneau Covers - Roll Up"): ("Truck Bed", "Tonneau Covers"),
    ("Tonneau Covers", "Tonneau Covers - Hard Fold"): ("Truck Bed", "Tonneau Covers"),
    ("Tonneau Covers", "Retractable Bed Covers"): ("Truck Bed", "Tonneau Covers"),
    ("Programmers & Chips", "Throttle Controllers"): ("Electronics", "Throttle Controllers"),
    ("Roofs & Roof Accessories", "Hard Top Accessories"): ("Exterior Accessories", "Hard Top Accessories"),
    ("Lights", "Lights Bed Rail"): ("Lighting", "Bed Rail Lights"),
    ("Suspension", "Strut Bars"): ("Suspension", "Strut Bars"),
    ("Forced Induction", "Reservoirs"): ("Forced Induction", "Reservoirs"),
    ("Exhaust, Mufflers & Tips", "Axle Back"): ("Exhaust", "Axle-Back Systems"),
}

